import {initial,act,view,catalog,type State,type Slot,type GameId,type Action} from '../games/engine.ts';
export type Member={id:string;name:string};
export type Challenge={id:string;title:string;description:string;deadline:string;kind:'daily'|'weekly'|'custom';completed:boolean[];skipped:boolean[];settled:boolean;created:number};
export type Photo={id:string;key:string;author:Slot;authorId:string;caption:string;created:number};
export type Room={name:string;created:number;members:[Member,Member|null];pending:{id:string;user:string;name:string}[];inviteHash:string;inviteUntil:number;balance:number;owned:string[];layout:Record<string,string>;game:{id:string;creator:Slot;status:'invited'|'active'|'finished'|'expired'|'abandoned';state:State;updated:number;endVotes:Slot[]}|null;history:{id:string;gameId:GameId;winner:Slot|null;scores:number[];date:number}[];challenges:Challenge[];ledger:{id:string;day:string;amount:number}[];messages:{id:string;author:Slot;authorId:string;text:string|null;parentId:string|null;created:number;read:boolean[]}[];photos:Photo[];receipts:string[]};
export const decorations=[{id:'plant',name:'窗边绿植',icon:'🪴',price:20,slot:'window'},{id:'flowers',name:'一束小花',icon:'🌷',price:20,slot:'table'},{id:'books',name:'一起读的书',icon:'📚',price:20,slot:'shelf'},{id:'mug',name:'情侣马克杯',icon:'☕',price:20,slot:'table'},{id:'cushion',name:'软软的抱枕',icon:'🧸',price:40,slot:'sofa'},{id:'lamp',name:'暖光小台灯',icon:'💡',price:40,slot:'shelf'},{id:'frame',name:'我们的相框',icon:'🖼️',price:40,slot:'wall'},{id:'rug',name:'奶油小地毯',icon:'🌼',price:40,slot:'floor'},{id:'cat',name:'打盹的小猫',icon:'🐈',price:60,slot:'sofa'},{id:'record',name:'复古唱片机',icon:'🎵',price:60,slot:'shelf'},{id:'lights',name:'星星小串灯',icon:'✨',price:60,slot:'wall'},{id:'fish',name:'小小水族箱',icon:'🐠',price:60,slot:'window'}];
export const templates=[['分享今日照片','留下一张今天的小风景'],['一起散步','走一段没有目的的路'],['推荐一首歌','分享一首想让对方听见的歌'],['一起做早餐','从一顿暖暖的早餐开始'],['夸夸对方','说一件你欣赏的小事'],['交换晚安','睡前留一句温柔的话'],['一起看电影','选一部两个人都感兴趣的电影'],['做一道新菜','一起试试没做过的菜'],['分享童年故事','讲一个小时候的有趣回忆'],['写一封小信','把平时没说的话写下来'],['一起看日落','找一个看晚霞的地方'],['为对方画张画','画得不像也没有关系'],['一起整理房间','让现实中的小屋也更舒服'],['约一次早餐','为周末预留一点慢时光'],['一起读十分钟','读喜欢的书，再交换感受'],['分享今日开心','记录今天开心的一瞬间'],['一起做甜点','把厨房变成甜甜的地方'],['一起骑车','选一条安全舒服的路线'],['一起逛书店','互相挑一本想读的书'],['一起看星星','认不出星座也能一起看'],['拍一张合照','把今天的我们留下来'],['说声谢谢','感谢对方最近做的一件小事'],['计划短途旅行','一起选一个想去的地方'],['一起玩一局','胜负之外，多陪彼此一会儿'],['分享一道美食','介绍最近吃到的好味道'],['学一句新表达','学一句温柔的外语或方言'],['一起喝杯茶','慢慢喝，慢慢聊'],['交换一个愿望','说出最近最想完成的事'],['一起做手作','做一个小小的共同作品'],['规划下次见面','留一件两个人都期待的事']];
export const dayKey=(now:number)=>new Date(now+8*3600000).toISOString().slice(0,10);
function weekKey(now:number){const d=new Date(now+8*3600000);d.setUTCDate(d.getUTCDate()-((d.getUTCDay()+6)%7));return d.toISOString().slice(0,10);}
function ensureChallenges(r:Room,now:number){for(const kind of ['daily','weekly'] as const){const key=kind==='daily'?dayKey(now):weekKey(now),n=Math.floor((Date.parse(key)/86400000));for(let i=0;i<3;i++){const id=`${kind}:${key}:${i}`;if(!r.challenges.some(c=>c.id===id)){const [title,description]=templates[((n*3+i+(kind==='weekly'?7:0))%templates.length+templates.length)%templates.length];r.challenges.push({id,title,description,deadline:kind==='daily'?key:dayKey(Date.parse(key)-8*3600000+6*86400000),kind,completed:[false,false],skipped:[false,false],settled:false,created:now});}}}if(r.challenges.length>150)r.challenges=r.challenges.slice(-150);}
export function newRoom(user:string,nick:string,name:string,now:number):Room{const r:Room={name:clean(name,30),created:now,members:[{id:user,name:clean(nick,20)},null],pending:[],inviteHash:'',inviteUntil:0,balance:0,owned:[],layout:{},game:null,history:[],challenges:[],ledger:[],messages:[],photos:[],receipts:[]};ensureChallenges(r,now);return r;}
function clean(v:unknown,max:number):string{if(typeof v!=='string'||!v.trim()||v.trim().length>max)throw Error(`请填写1到${max}字的内容`);return v.trim();}
function reward(r:Room,id:string,amount:number,now:number){if(r.ledger.some(e=>e.id===id))return;const day=dayKey(now),used=r.ledger.filter(e=>e.day===day).reduce((a,e)=>a+e.amount,0),granted=Math.max(0,Math.min(amount,50-used));r.ledger.push({id,day,amount:granted});r.balance+=granted;}
function recordGame(r:Room,now:number){const g=r.game!;if(r.history.some(h=>h.id===g.id))return;r.history.push({id:g.id,gameId:g.state.id,winner:g.state.winner,scores:g.state.scores,date:now});r.history=r.history.slice(-100);reward(r,`game:${g.id}`,5,now);}
function expire(r:Room,now:number){if(r.game&&['invited','active'].includes(r.game.status)&&now-r.game.updated>=7*86400000)r.game.status='expired';}
export function transition(room:Room,p:Slot,op:string,b:Record<string,unknown>,now:number):Room{
 const r=structuredClone(room);if(!r.members[p])throw Error('你已离开这个小屋');ensureChallenges(r,now);expire(r,now);
 switch(op){
  case 'game-create':{if(!r.members[1])throw Error('配对后就能一起玩啦');if(r.game&&['active','invited'].includes(r.game.status))throw Error('先完成或结束当前这局');const gameId=b.id as GameId;if(!catalog.some(g=>g.id===gameId))throw Error('没有这个游戏');const seed=crypto.getRandomValues(new Uint32Array(1))[0];r.game={id:crypto.randomUUID(),creator:p,status:'invited',state:initial(gameId,seed),updated:now,endVotes:[]};break;}
  case 'game-accept':{if(!r.game||r.game.status!=='invited'||r.game.creator===p)throw Error('等待对方接受邀请');r.game.status='active';r.game.updated=now;break;}
  case 'game-action':{if(!r.game||r.game.status!=='active')throw Error('等待对方加入，或者开始新一局');r.game.state=act(r.game.state,p,b as Action);r.game.updated=now;if(r.game.state.done){r.game.status='finished';recordGame(r,now);}break;}
  case 'game-resign':{if(!r.game||!['active','invited'].includes(r.game.status))throw Error('没有进行中的游戏');r.game.status='abandoned';r.game.updated=now;break;}
  case 'game-end':{if(!r.game||r.game.status!=='active')throw Error('没有进行中的游戏');if(!r.game.endVotes.includes(p))r.game.endVotes.push(p);if(r.game.endVotes.length===2)r.game.status='abandoned';break;}
  case 'challenge-create':{if(r.challenges.filter(c=>c.kind==='custom'&&!c.settled&&!c.skipped.every(Boolean)).length>=50)throw Error('先完成一些现有挑战吧');const title=clean(b.title,40),description=typeof b.description==='string'?b.description.trim().slice(0,300):'',deadline=typeof b.deadline==='string'?b.deadline:'';if(deadline&&(!/^\d{4}-\d{2}-\d{2}$/.test(deadline)||!Number.isFinite(Date.parse(deadline))||deadline<dayKey(now)))throw Error('截止日期不能早于今天');r.challenges.push({id:crypto.randomUUID(),title,description,deadline,kind:'custom',completed:[false,false],skipped:[false,false],settled:false,created:now});break;}
  case 'challenge-complete':case 'challenge-skip':{const c=r.challenges.find(c=>c.id===b.id);if(!c)throw Error('找不到这个挑战');if(c.settled)break;if(c.deadline&&c.deadline<dayKey(now))throw Error('挑战已经过期，试试新的吧');if(op==='challenge-skip')c.skipped[p]=true;else{c.completed[p]=true;c.skipped[p]=false;if(c.completed.every(Boolean)){c.settled=true;reward(r,`challenge:${c.id}`,10,now);}}break;}
  case 'buy':{const d=decorations.find(d=>d.id===b.id);if(!d)throw Error('找不到这件装饰');if(r.owned.includes(d.id))break;if(r.balance<d.price)throw Error('星星还不够，去一起玩一会儿吧');r.balance-=d.price;r.owned.push(d.id);break;}
  case 'place':{const d=decorations.find(d=>d.id===b.id);if(!d||!r.owned.includes(d.id)||b.slot!==d.slot)throw Error('请放到装饰对应的位置');r.layout[d.slot]=d.id;break;}
  case 'message':{const text=clean(b.text,1000),parentId=typeof b.parentId==='string'?b.parentId:null;if(parentId&&!r.messages.some(m=>m.id===parentId))throw Error('原留言不存在');r.messages.push({id:crypto.randomUUID(),author:p,authorId:r.members[p]!.id,text,parentId,created:now,read:[p===0,p===1]});if(r.messages.length>200)throw Error('信箱已满，清理一些旧留言再写吧');break;}
  case 'message-delete':{const m=r.messages.find(m=>m.id===b.id);if(!m||m.authorId!==r.members[p]!.id)throw Error('只能删除自己的留言');m.text=null;break;}
  case 'message-read':{for(const m of r.messages)m.read[p]=true;break;}
  case 'profile':{r.members[p]!.name=clean(b.name,20);if(b.roomName!==undefined)r.name=clean(b.roomName,30);break;}
  case 'invite-renew':{if(p!==0||r.members[1])throw Error('只有创建者可在未配对时生成邀请');break;}
  default:throw Error('未知操作');
 }return r;
}
export function snapshot(room:Room,p:Slot,now:number){const r=structuredClone(room);ensureChallenges(r,now);expire(r,now);const {inviteHash,inviteUntil,receipts,...publicRoom}=r;return {...publicRoom,members:r.members.map(m=>m?{name:m.name}:null),pending:p===0?r.pending.map(({id,name})=>({id,name})):[],slot:p,game:r.game?{...r.game,state:view(r.game.state,p)}:null,earnedToday:r.ledger.filter(e=>e.day===dayKey(now)).reduce((a,e)=>a+e.amount,0),ledger:undefined,messages:r.messages.map(({authorId,...m})=>({...m,own:authorId===r.members[p]!.id})),photos:r.photos.map(({key,authorId,...photo})=>({...photo,own:authorId===r.members[p]!.id})),day:dayKey(now)};}

