import {BaseStore,AppError,type Actor} from './store.ts';
import {snapshot,type Room} from './model.ts';
import {memberEpoch} from '../realtime/room-policy.ts';
type Env={DB?:D1Database;ROOM_REALTIME?:DurableObjectNamespace};
export async function roomViews(roomId:string,version:number,room:Room,now:number){return [0,1].map(slot=>({roomId,version,room:room.members[slot]?snapshot(room,slot as 0|1,now):null,pending:null}));}
export async function notifyCommitted(publish:()=>Promise<void>){try{await publish();return true;}catch{return false;}}
export async function issueTicket(env:Env,actor:Actor,origin:string){if(!env.DB||!env.ROOM_REALTIME)throw new AppError('实时连接暂不可用',503);const store=new BaseStore(env.DB),membership=await store.membership(actor);if(!membership)throw new AppError('请先进入小屋',403);const row=await store.raw(membership.room_id),room=JSON.parse(row.data) as Room,epoch=await memberEpoch(room.members,room.membershipGeneration);const stub=env.ROOM_REALTIME.get(env.ROOM_REALTIME.idFromName(row.id));const response=await stub.fetch(new Request('https://room.internal/ticket',{method:'POST',body:JSON.stringify({roomId:row.id,userId:actor.userId,slot:membership.slot,epoch,origin})}));if(!response.ok)throw new AppError('实时连接暂不可用',503);const data=await response.json() as {ticket:string;expires:number};return {...data,url:`/api/base/realtime?room=${encodeURIComponent(row.id)}&ticket=${encodeURIComponent(data.ticket)}`};}
export async function upgradeRealtime(request:Request,env:Env){const url=new URL(request.url),roomId=url.searchParams.get('room')||'',ticket=url.searchParams.get('ticket')||'';if(!env.ROOM_REALTIME)return new Response('Realtime unavailable',{status:503});if(!/^[a-zA-Z0-9-]{1,80}$/.test(roomId)||!/^[a-f0-9]{64}$/.test(ticket))return new Response('Invalid ticket',{status:403});const target=new URL('https://room.internal/connect');target.searchParams.set('ticket',ticket);return env.ROOM_REALTIME.get(env.ROOM_REALTIME.idFromName(roomId)).fetch(new Request(target,{method:'GET',headers:request.headers}));}
export async function publishRoom(env:Env,roomId:string){if(!env.ROOM_REALTIME)return;const response=await env.ROOM_REALTIME.get(env.ROOM_REALTIME.idFromName(roomId)).fetch(new Request('https://room.internal/publish',{method:'POST',body:JSON.stringify({roomId})}));if(!response.ok)throw Error('Realtime publication unavailable');}
export const revokeRoom=publishRoom;
export async function roomVersion(env:Env,actor:Actor){if(!env.DB)throw new AppError('存档暂不可用',503);const store=new BaseStore(env.DB),m=await store.membership(actor);if(!m)return {roomId:null,version:0,epoch:''};const row=await store.raw(m.room_id);return {roomId:row.id,version:row.version,epoch:await memberEpoch((JSON.parse(row.data) as Room).members,(JSON.parse(row.data) as Room).membershipGeneration)};}
