/* eslint-disable */
// Generated by Wrangler by running `wrangler types cloudflare-bindings.d.ts --config wrangler.jsonc --include-runtime false` (hash: 89d9cea1a26969ac68fe5b0dc884f704)
interface __BaseEnv_Env {
	DB: D1Database;
	AUTH_MODE: "key";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./build/cloudflare-worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AUTH_MODE">> {}
}
