'use client';
import PrivatePhoto from './PrivatePhoto';
import PhotoViewer from './PhotoViewer';
import {privatePhotos} from '@/src/photo-cache';
import {preparePhoto} from '@/src/prepare-photo';
import {formatPublishedTime} from '@/src/display-time';
import {invitationLink,readInvitation} from '@/src/invites';
import {createReadTracker} from '@/src/read-receipts';
import {useState,useEffect,useRef,useCallback,type ReactNode} from 'react';
import {House,Gamepad2,Flag,Heart,ChevronRight,Plus,X,Settings2,Star,Mail,Camera,ArrowLeft,Leaf,Check,Copy,WifiOff} from 'lucide-react';
import RoomScene from './RoomScene';import GamePlay,{type VisibleState} from './GamePlay';
import {catalog,type Action,type GameId} from '@/src/games/engine';
import {decorations,type snapshot} from '@/src/server/model';
type Mine={roomId:string|null;version:number;room:ReturnType<typeof snapshot>|null;pending:{roomName:string}|null};
type Tab='room'|'games'|'challenges'|'us';
type Modal='create'|'join'|'invite'|'shop'|'letters'|'photos'|'challenge'|'settings'|'leave'|null;
const empty:Mine={roomId:null,version:0,room:null,pending:null};
function date(n:number){return new Date(n).toLocaleDateString('zh-CN',{timeZone:'Asia/Shanghai',month:'short',day:'numeric'});}
export default function BaseApp({signedIn,displayName,standalone=false,authHref='/signin-with-chatgpt?return_to=%2F'}:{signedIn:boolean;displayName:string;standalone?:boolean;authHref?:string}){
 const [mine,setMine]=useState<Mine>(empty),[tab,setTab]=useState<Tab>('room'),[modal,setModal]=useState<Modal>(null),[busy,setBusy]=useState(false),[loading,setLoading]=useState(signedIn),[error,setError]=useState(''),[toast,setToast]=useState(''),[filter,setFilter]=useState('全部'),[challengeFilter,setChallengeFilter]=useState('daily'),[gameOpen,setGameOpen]=useState(false),[inviteCode,setInviteCode]=useState(''),[nick,setNick]=useState(displayName),[roomName,setRoomName]=useState('我们的小满'),[joinCode,setJoinCode]=useState(''),[message,setMessage]=useState(''),[reply,setReply]=useState<string|null>(null),[title,setTitle]=useState(''),[description,setDescription]=useState(''),[deadline,setDeadline]=useState(''),[caption,setCaption]=useState(''),[photo,setPhoto]=useState<File|null>(null),[photoView,setPhotoView]=useState<string|null>(null);
 const readTracker=useRef(createReadTracker()),linkEntered=useRef('');const etag=useRef(''),inFlight=useRef(false),locked=useRef(false),retry=useRef(0);const room=mine.room,slot=room?.slot||0,names=room?.members.map((m,i)=>m?.name||(i===1?'另一位小屋主人':'小屋主人'))||['你','对方'];
 const refresh=useCallback(async(force=false)=>{if(!signedIn||inFlight.current)return;inFlight.current=true;try{const res=await fetch('/api/base/mine',{headers:!force&&etag.current?{'If-None-Match':etag.current}:{},cache:'no-store'});if(res.status!==304){const data=await res.json() as Mine & {error?:string};if(!res.ok)throw Error(data.error||'小屋暂时没连接上');etag.current=res.headers.get('etag')||'';setMine(data);}setError('');retry.current=0;}catch(e){retry.current++;setError(e instanceof Error?e.message:'连接暂时中断');}finally{setLoading(false);inFlight.current=false;}},[signedIn]);
 useEffect(()=>{refresh(true);let timer:ReturnType<typeof setTimeout>;const loop=()=>{timer=setTimeout(async()=>{if(!document.hidden)await refresh();loop();},retry.current===0?2000:[5000,10000,30000][Math.min(retry.current-1,2)]);};loop();const visible=()=>{if(!document.hidden)refresh(true);};document.addEventListener('visibilitychange',visible);return()=>{clearTimeout(timer);document.removeEventListener('visibilitychange',visible);};},[refresh]);
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),4000);return()=>clearTimeout(t);},[toast]);
 const post=async(path:string,body:Record<string,unknown>)=>{if(locked.current)return null;if(!navigator.onLine){setToast('网络断开了，连接后再试');return null;}locked.current=true;setBusy(true);try{const res=await fetch(`/api/base/${path}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),data=await res.json() as Record<string,string>;if(!res.ok){if(res.status===409)await refresh(true);throw Error(data.error||'没有保存成功');}await refresh(true);return data as Record<string,unknown>;}catch(e){setToast(e instanceof Error?e.message:'没有保存成功，内容还在，请重试');return null;}finally{locked.current=false;setBusy(false);}};
 const pendingIntents=useRef(new Map<string,string>());
 const mutate=async(op:string,payload:Record<string,unknown>={})=>{const key=JSON.stringify([op,payload]);let requestId=pendingIntents.current.get(key);if(!requestId){requestId=crypto.randomUUID();pendingIntents.current.set(key,requestId);}const saved=!!await post('action',{op,payload,version:mine.version,requestId});if(saved)pendingIntents.current.delete(key);return saved;};
 const requireRoom=()=>{if(!signedIn){window.location.href=authHref;return false;}if(!room){setModal(mine.pending?'invite':'create');return false;}return true;};
 const open=(place:string)=>{if(place==='games'){setTab('games');return;}if(requireRoom()){setModal(place as Modal);if(place==='letters')readTracker.current.reset();}};
 const launch=async(id:GameId)=>{if(!requireRoom())return;if(room?.game&&['active','invited'].includes(room.game.status)){setGameOpen(true);setToast('先继续当前这一局吧');return;}if(await mutate('game-create',{id})){setGameOpen(true);setTab('games');setToast('邀请已放进小屋，等对方来玩');}};
 const makeInvitation=async()=>{const data=await post('renew',{});if(data){setInviteCode(String(data.inviteCode));setModal('invite');}};
 const copy=async()=>{try{await navigator.clipboard.writeText(inviteCode);setToast('邀请码已复制，发给对方就好');}catch{setToast('长按邀请码即可复制');}};
 const upload=async()=>{if(!photo||locked.current)return;locked.current=true;setBusy(true);try{const blob=await preparePhoto(photo,standalone);const res=await fetch('/api/base/photo',{method:'POST',headers:{'Content-Type':blob.type,'X-Photo-Caption':encodeURIComponent(caption)},body:blob}),data=await res.json() as Record<string,string>;if(!res.ok)throw Error(data.error||'上传失败');setPhoto(null);setCaption('');setToast('这一刻，已经收藏好');await refresh(true);}catch(e){setToast(e instanceof Error?e.message:'照片上传失败，请重试');}finally{locked.current=false;setBusy(false);}};

 useEffect(()=>{privatePhotos.clear();setPhotoView(null);return()=>privatePhotos.clear();},[mine.roomId]);
 useEffect(()=>{const mark=()=>{if(modal!=='letters'||document.hidden||!navigator.onLine||locked.current||!room?.messages.some(m=>m.text&&!m.read[slot]))return;void readTracker.current.mark(mine.roomId+':'+mine.version,()=>mutate('message-read'));};const online=()=>{readTracker.current.reset();mark();};mark();const timer=setInterval(mark,5000);document.addEventListener('visibilitychange',mark);window.addEventListener('online',online);return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',mark);window.removeEventListener('online',online);};},[modal,mine.version,busy]);
 const share=async(kind:'invite'|'play',value:string)=>{const url=invitationLink(window.location.href,kind,value),title=kind==='play'?'来小满，和我一起玩一局':'来小满，加入我们的双人小屋';if(navigator.share){try{await navigator.share({title,text:title,url});return;}catch(e){if(e instanceof Error&&e.name==='AbortError')return;}}try{await navigator.clipboard.writeText(url);setToast('邀请链接已复制，粘贴到微信发给对方');}catch{setToast('请长按下方邀请链接复制');}};
 useEffect(()=>{if(!signedIn||loading)return;const link=readInvitation(window.location.href);if(link.invite&&!room&&!mine.pending){setJoinCode(link.invite);setModal('join');}if(link.play&&room?.game?.id===link.play&&linkEntered.current!==link.play){setTab('games');setGameOpen(true);if(room.game.status==='invited'&&room.game.creator!==slot){if(locked.current)return;linkEntered.current=link.play;void mutate('game-accept');}else linkEntered.current=link.play;}},[signedIn,loading,mine.version,busy]);
 const unread=room?.messages.filter(m=>!m.read[slot]).length||0;
 return <div className="app-shell"><header className="app-header"><button className="brand" onClick={()=>{setTab('room');setGameOpen(false);}} aria-label="回到小屋"><span className="brand-house"><House size={23}/><i>♥</i></span><span>小满<small>LITTLE HIDEAWAY</small></span></button><div className="header-right">{standalone&&signedIn&&<a className="icon-button" aria-label="保存我的私人钥匙" href={authHref}>🗝️</a>}<span className="star-wallet"><Star size={15} fill="currentColor"/>{room?.balance||0}<small>星星</small></span><button className="icon-button" aria-label="小屋设置" onClick={()=>{if(requireRoom()){setNick(names[slot]);setRoomName(room!.name);setModal('settings');}}}><Settings2 size={19}/></button></div></header>
 <main className="main-content">{error&&<div className="connection-banner" role="status"><WifiOff size={16}/><span>{error}</span><button onClick={()=>refresh(true)}>重试</button></div>}
 {tab==='room'&&<><div className="page-heading"><div><p className="eyebrow">OUR LITTLE HOME</p><h1>{room?.name||'把日子，过成我们的小满'} <span>✿</span></h1><p>{room?'今天也留一点时间，给我们。':'一间小屋，两个人，很多可爱的小日子。'}</p></div><span className="handnote">有你就刚刚好 ♡</span></div>
 <section className="home-card"><div className="home-card-top"><div className="residents"><span className="avatar bunny">🐰</span><span className="avatar fox">🦊</span><div><b>{room?(room.members[1]?`${names[0]} & ${names[1]}`:`${names[0]}的小屋`):'等你们一起住进来'}</b><small>{room?.members[1]?'两个人的秘密，都在这里':room?'另一把钥匙，留给心里的那个人':'从一把小小的钥匙开始'}</small></div></div><button className="outline small" onClick={()=>open('shop')}><Leaf size={14}/>布置小屋</button></div><RoomScene layout={room?.layout} onOpen={open}/><div className="home-footer"><span><span className="status-dot"/>{loading?'正在打开小屋…':room?.members[1]?'共同存档 · 自动同步':'温暖的小屋，随时等你回来'}</span><span>慢慢来，日子还长</span></div></section>
 {!room?<section className="welcome-card"><span className="welcome-icon">🗝️</span><div><h3>{mine.pending?'邀请已经送到对方手里':'给我们一个专属的小地方'}</h3><p>{mine.pending?`等“${mine.pending.roomName}”的主人确认，就能一起入住。`:'玩一局、留句话，把共同的回忆一点点装进来。'}</p></div><div className="welcome-actions">{!signedIn?<a className="primary" href={authHref} target="_top">领取小屋钥匙 <ChevronRight size={16}/></a>:mine.pending?<button className="outline" onClick={()=>refresh(true)}>看看确认结果</button>:<><button className="primary" onClick={()=>setModal('create')}>创建我们的小屋</button><button className="text-button" onClick={()=>setModal('join')}>我有邀请码</button></>}</div></section>:!room.members[1]?<section className="welcome-card"><span className="welcome-icon">💌</span><div><h3>另一位小屋主人，还在路上</h3><p>生成邀请码，分享给对方。收到申请后由你确认。</p>{room.pending.map(p=><div className="join-request" key={p.id}><span>{p.name}想加入小屋</span><button className="primary small" disabled={busy} onClick={async()=>{if(await post('confirm',{joinId:p.id}))setToast('欢迎你们一起入住！');}}>确认配对</button></div>)}</div><button className="primary" disabled={busy} onClick={makeInvitation}>邀请对方</button></section>:null}
 <div className="home-bottom-grid"><button className="feature-note letter-note" onClick={()=>open('letters')}><span className="note-icon"><Mail size={26}/>{unread>0&&<i>{unread}</i>}</span><div><small>给心里的那个人</small><h3>{room?.messages.length?'有些话，只想告诉你':'留一句今天的想念'}</h3><p>{room?.messages.filter(m=>m.text).at(-1)?.text||'再平凡的一天，也值得被你听见。'}</p></div><ChevronRight size={18}/></button><button className="feature-note game-note" onClick={()=>{setTab('games');setGameOpen(!!room?.game&&['active','invited'].includes(room.game.status));}}><span className="note-icon"><Gamepad2 size={29}/></span><div><small>我们的双人游乐厅</small><h3>{room?.game&&['active','invited'].includes(room.game.status)?'还有一局，等我们继续':'今天，玩一点什么？'}</h3><p>{catalog.length}种小游戏 · 合作、对战和小默契</p></div><ChevronRight size={18}/></button></div><div className="quiet-footer">把普通的一天，收藏成喜欢的一天。 <Heart size={12}/></div></>}
 {tab==='games'&&<><div className="page-heading"><div><p className="eyebrow">PLAY A LITTLE, LOVE A LITTLE</p><h1>双人游乐厅 <span>✧</span></h1><p>不一定要赢，但一定要一起开心。</p></div><span className="round-badge">{catalog.length}<small>种小乐趣</small></span></div>
 {gameOpen&&room?.game?<section className="play-card"><button className="text-button back" onClick={()=>setGameOpen(false)}><ArrowLeft size={16}/>所有游戏</button><div className="play-heading"><span className={`game-icon ${catalog.find(g=>g.id===room.game!.state.id)?.color}`}>{catalog.find(g=>g.id===room.game!.state.id)?.icon}</span><div><h2>{catalog.find(g=>g.id===room.game!.state.id)?.name}</h2><p>{names.join(' & ')}</p></div></div><details className="rules"><summary>怎么玩？</summary><p>{catalog.find(g=>g.id===room.game!.state.id)?.rule}</p></details>
 {room.game.status==='invited'?<div className="empty-state"><span>🎮</span><h3>{room.game.creator===slot?'邀请已送达，等你来玩':'对方邀请你一起玩'}</h3><div className="ready-players">{names.map((name,i)=><div key={i} className={i===room.game!.creator?'ready':''}><span>{i===0?'🐰':'🦊'}</span><b>{name}</b><small>{i===room.game!.creator?'✓ 已准备':'○ 未准备'}</small></div>)}</div><p>等待另一位准备，双方准备后就能开始。进度会自动保存。</p><button className="outline" onClick={()=>share('play',room.game!.id)}>分享这局邀请到微信</button><a className="invite-share-link" href={invitationLink(window.location.href,'play',room.game.id)}>长按复制游戏邀请链接</a>{room.game.creator!==slot&&<button className="primary" disabled={busy} onClick={()=>mutate('game-accept')}>好呀，一起玩</button>}<button className="text-button" disabled={busy} onClick={()=>mutate('game-resign')}>取消这局</button></div>:['expired','abandoned'].includes(room.game.status)?<div className="empty-state"><span>🌿</span><h3>{room.game.status==='expired'?'这一局已过期':'这一局已经结束'}</h3><p>没有计入输赢，也没有发放奖励。</p><button className="primary" disabled={busy} onClick={()=>launch(room.game!.state.id!)}>重新邀请一局</button></div>:<><div className="player-strip">{names.map((name,i)=><span key={i} className={i===slot?'you':''}>{i===0?'🐰':'🦊'} {name}{i===slot?'（你）':''} · 已准备</span>)}</div>{room.game.state.done&&<div className="result-card"><span>✦</span><h3>{['quiz','predict','ranking','chemistry'].includes(room.game.state.id||'')?'属于我们的答案，揭晓啦':['puzzle','maze','escape','draw','match'].includes(room.game.state.id||'')?cooperativeResult(room.game.state):room.game.state.winner===null?'打成平手，再玩一局？':`${names[room.game.state.winner||0]}赢啦！`}</h3><p>{room.game.state.id==='reflex'?`中位成绩：${room.game.state.scores?.join(' / ')} ms`:`共同完成一局 · 今日已获得 ${room.earnedToday} 星星`}</p>{['quiz','predict','ranking','chemistry'].includes(room.game.state.id||'')&&<p>本局得分：{room.game.state.scores?.join(' / ')} · 满分{room.game.state.id==='chemistry'?8:5}</p>}<button className="primary" disabled={busy} onClick={()=>launch(room.game!.state.id!)}>再来一局</button></div>}<GamePlay key={room.game.id} state={room.game.state} slot={slot} names={names} busy={busy} onAction={(a:Action)=>mutate('game-action',a)}/>{!room.game.state.done&&<div className="end-actions"><button className="text-button" disabled={busy} onClick={()=>{if(confirm('退出本局？当前进度会结束，不计输赢和奖励。'))mutate('game-resign');}}>退出本局</button><button className="text-button" disabled={busy||room.game.endVotes.includes(slot)} onClick={()=>mutate('game-end')}>{room.game.endVotes.includes(slot)?'已申请结束，等对方':room.game.endVotes.length?'同意结束这局':'申请共同结束'}</button></div>}</>}
 </section>:<>{room?.game&&['active','invited'].includes(room.game.status)&&<button className="current-game" onClick={()=>setGameOpen(true)}><Gamepad2 size={22}/><span><b>继续我们的{catalog.find(g=>g.id===room.game!.state.id)?.name}</b><small>{room.game.status==='invited'?'一份邀请在等你':'上次的进度已经保存好'}</small></span><ChevronRight size={20}/></button>}<div className="filter-tabs">{['全部','对战','默契','合作'].map(t=><button key={t} className={filter===t?'active':''} onClick={()=>setFilter(t)}>{t==='全部'?'全部游戏':t}</button>)}</div><div className="game-grid">{catalog.filter(g=>filter==='全部'||g.tag===filter).map((g,i)=><button key={g.id} className={`game-card ${g.color}`} disabled={busy} onClick={()=>launch(g.id)}><div className="game-card-top"><span className={`game-icon ${g.color}`}>{g.icon}</span><span className="game-tag">{g.tag}</span></div><h3>{g.name}</h3><p>{g.description}</p><div className="game-card-bottom"><span>{g.id==='reflex'?'各自计时':'支持错时接续'}</span><span>一起玩 <ChevronRight size={14}/></span></div>{i===0&&filter==='全部'&&<span className="recommend-label">从这一局开始 ♡</span>}</button>)}</div><p className="section-footnote">完整玩完一局，小屋获得5颗星星。输了也有奖励，开心最重要。</p></>}
 </>}
 {tab==='challenges'&&<><div className="page-heading"><div><p className="eyebrow">LITTLE THINGS, TOGETHER</p><h1>一起做的小事 <span>❀</span></h1><p>把“有空一起”，变成“今天一起”。</p></div><button className="outline" onClick={()=>{if(requireRoom())setModal('challenge');}}><Plus size={16}/>自定义</button></div><div className="challenge-banner"><span>🌷</span><div><h3>每一件小事，都在让我们靠近</h3><p>两人都完成，获得10颗星星。不赶进度，也没有连续签到压力。</p></div></div><div className="filter-tabs">{[['daily','今天'],['weekly','本周'],['custom','我们的约定'],['history','已完成']].map(([id,t])=><button key={id} className={challengeFilter===id?'active':''} onClick={()=>setChallengeFilter(id)}>{t}</button>)}</div>{!room?<Empty icon="🌱" title="配对后，开始收集共同的小事" text="创建或加入小屋，就能看到今天的挑战。" action={()=>requireRoom()}/>:<div className="challenge-list">{room.challenges.filter(c=>challengeFilter==='history'?c.settled:c.kind===challengeFilter&&!c.settled&&(!c.deadline||c.deadline>=room.day)).map((c,i)=><article className={`challenge-card ${c.completed[slot]?'completed':''}`} key={c.id}><div className="challenge-number">{c.settled?<Check size={20}/>:String(i+1).padStart(2,'0')}</div><div className="challenge-body"><div className="challenge-title"><h3>{c.title}</h3><span>✦ 10</span></div><p>{c.description}</p><div className="challenge-members">{names.map((name,p)=><span key={p} className={c.completed[p]?'done':''}>{c.completed[p]?'✓':'○'} {name}</span>)}{c.deadline&&<small>截至 {c.deadline.slice(5)}</small>}</div></div><div className="challenge-actions">{c.settled?<span className="muted">一起完成啦</span>:<><button className={c.completed[slot]?'outline':'primary'} disabled={busy||c.completed[slot]} onClick={()=>mutate('challenge-complete',{id:c.id})}>{c.completed[slot]?'已完成，等你':'我完成啦'}</button><button className="text-button" disabled={busy||c.skipped[slot]} onClick={()=>mutate('challenge-skip',{id:c.id})}>{c.skipped[slot]?'今天先跳过':'先跳过'}</button></>}</div></article>)}{!room.challenges.some(c=>challengeFilter==='history'?c.settled:c.kind===challengeFilter&&!c.settled&&(!c.deadline||c.deadline>=room.day))&&<Empty icon="🍃" title={challengeFilter==='history'?'共同完成的小事，会留在这里':'这里还没有约定'} text="可以写一个只属于你们的小挑战。" action={()=>setModal('challenge')}/>}</div>}</>}
 {tab==='us'&&<><div className="page-heading"><div><p className="eyebrow">YOU, ME & OUR DAYS</p><h1>我们的小日子 <span>♡</span></h1><p>不是每一天都特别，但每一天都属于我们。</p></div></div>{room?<><section className="couple-card"><div className="couple-avatars"><span>🐰</span><Heart size={23}/><span>🦊</span></div><h2>{room.members[1]?names.join(' & '):`${names[0]}，等另一位主人`}</h2><p>从 {date(room.created)} 开始，我们一起拥有这个小地方</p><div className="stats-grid"><div><b>{Math.max(1,Math.floor((Date.now()-room.created)/86400000)+1)}</b><span>小屋的第几天</span></div><div><b>{room.history.length}</b><span>共同玩过的局</span></div><div><b>{room.challenges.filter(c=>c.settled).length}</b><span>完成的小事</span></div></div></section><div className="us-shortcuts"><button onClick={()=>open('letters')}><Mail size={23}/><span>我们的信箱<small>{unread?`${unread}条新留言`:'每一句话，都值得被收藏'}</small></span><ChevronRight size={18}/></button><button onClick={()=>open('photos')}><Camera size={23}/><span>回忆相册<small>{room.photos.length} / 100张小日子</small></span><ChevronRight size={18}/></button><button onClick={()=>open('shop')}><Leaf size={23}/><span>小屋收藏<small>已收集 {room.owned.length} / 12件装饰</small></span><ChevronRight size={18}/></button></div><div className="section-title"><h3>最近一起玩过</h3><span>只记录，不排名</span></div>{room.history.length?<div className="history-list">{[...room.history].reverse().slice(0,15).map(h=><div key={h.id}><span>{catalog.find(g=>g.id===h.gameId)?.icon}</span><div><b>{catalog.find(g=>g.id===h.gameId)?.name}</b><small>{['quiz','predict','ranking','puzzle','maze','escape','draw','chemistry','match'].includes(h.gameId)?'共同游玩':h.winner===null?'平局':`${names[h.winner]}获胜`}</small></div><small>{date(h.date)}</small></div>)}</div>:<div className="mini-empty">我们的第一局，还等着我们一起开始。</div>}</>:<Empty icon="♡" title="这里，慢慢写下我们的故事" text="配对后，回忆和共同成绩都会留在这里。" action={()=>requireRoom()}/>}</>}
 </main><nav className="bottom-nav" aria-label="主要导航">{([{id:'room',label:'小屋',Icon:House},{id:'games',label:'游戏',Icon:Gamepad2},{id:'challenges',label:'挑战',Icon:Flag},{id:'us',label:'我们',Icon:Heart}] as const).map(({id,label,Icon})=><button key={id} className={tab===id?'active':''} aria-current={tab===id?'page':undefined} onClick={()=>{setTab(id);setGameOpen(false);window.scrollTo({top:0,behavior:'smooth'});}}><Icon size={22} strokeWidth={tab===id?2.2:1.6}/><span>{label}</span>{id==='games'&&room?.game?.status==='invited'&&room.game.creator!==slot&&<i/>}</button>)}</nav>
 {toast&&<div className="toast" role="status">{toast}</div>}
 {modal&&<ModalBox title={{create:'给我们的小屋起个名字',join:'拿着钥匙，来找你',invite:'另一把钥匙，交给你',shop:'把小屋布置成喜欢的样子',letters:'有些话，只想告诉你',photos:'收藏我们的小日子',challenge:'写一个共同的小约定',settings:'小屋里的我们',leave:'离开这间小屋'}[modal]} onClose={()=>setModal(null)}>
 {['create','join'].includes(modal)&&<form className="form-stack" onSubmit={async e=>{e.preventDefault();const data=await post(modal,{nick,name:roomName,code:joinCode});if(data){if(modal==='create'){setInviteCode(String(data.inviteCode));setModal('invite');}else{setModal(null);setToast('申请已送达，等对方确认');}}}}><label>你的小屋昵称<input required maxLength={20} placeholder="对方平时怎么叫你？" value={nick} onChange={e=>setNick(e.target.value)}/></label>{modal==='create'?<label>小屋的名字<input required maxLength={30} value={roomName} onChange={e=>setRoomName(e.target.value)}/></label>:<label>12位邀请码<input required className="code-input" placeholder="输入对方发来的钥匙" maxLength={12} value={joinCode} onChange={e=>setJoinCode(e.target.value.toUpperCase().replace(/[^A-F0-9]/g,''))}/></label>}<p className="muted">{standalone?'使用各自的私人钥匙登录，换手机也能回到同一间小屋。':'使用各自的ChatGPT账号登录，换手机也能回到同一间小屋。'}</p><button className="primary wide" disabled={busy}>{busy?'正在准备…':modal==='create'?'创建小屋，拿到钥匙':'申请加入小屋'}</button></form>}
 {modal==='invite'&&<div className="invite-content"><span>🗝️</span>{mine.pending&&!room?<><h3>等对方确认一下</h3><p>你的申请已经送到“{mine.pending.roomName}”，可以稍后回来。</p></>:<><p>把这把钥匙，发给想一起住进来的人。</p>{inviteCode?<><button className="invite-code" onClick={copy}>{inviteCode}<Copy size={17}/></button><button className="outline wide" onClick={()=>share('invite',inviteCode)}>分享小屋邀请到微信</button><a className="invite-share-link" href={invitationLink(window.location.href,'invite',inviteCode)}>长按复制小屋邀请链接</a><p className="muted">24小时有效 · 只能配对一位成员<br/>确认配对后，邀请码失效。</p></>:<button className="primary" disabled={busy} onClick={makeInvitation}>生成新邀请码</button>}<p className="muted">{standalone?'对方点开链接后保存自己的私人钥匙，再申请加入。你确认后，就能一起玩；无需分享你的私人钥匙。':'分享邀请码前，请为对方设置网站访问权限。'}</p></>}</div>}
 {modal==='shop'&&room&&<><div className="shop-intro"><span>✦ {room.balance} 颗星星</span><small>今日已获得 {room.earnedToday} 星星</small></div><p className="muted">一起玩一局 +5，完成双人挑战 +10。每日获得星星不限额。</p><div className="shop-grid">{decorations.map(d=><article key={d.id}><span>{d.icon}</span><h4>{d.name}</h4><small>{({window:'窗边',table:'桌上',shelf:'书架',sofa:'沙发',wall:'墙面',floor:'地板'} as Record<string,string>)[d.slot]}</small>{room.owned.includes(d.id)?<button className="outline" disabled={busy||room.layout[d.slot]===d.id} onClick={()=>mutate('place',{id:d.id,slot:d.slot})}>{room.layout[d.slot]===d.id?'已经摆好':'摆进小屋'}</button>:<button className="primary" disabled={busy||room.balance<d.price} onClick={async()=>{if(await mutate('buy',{id:d.id}))setToast(`收集到${d.name}，可以摆进小屋了`);}}>✦ {d.price}</button>}</article>)}</div></>}
 {modal==='letters'&&room&&<><div className="letters-list">{room.messages.length?[...room.messages].reverse().map(m=><article key={m.id} className={m.own?'own':''}><div><b>{(m as typeof m&{authorName?:string}).authorName||names[m.author]}</b><small>{formatPublishedTime(m.created)}{m.own?` · ${m.read[1-slot]?'对方已读':'对方未读'}`:''}</small></div>{m.parentId&&<blockquote>回复：{room.messages.find(x=>x.id===m.parentId)?.text?.slice(0,80)||'原留言已删除'}</blockquote>}<p>{m.text||'这条留言已被作者收回'}</p>{m.text&&<footer><button className="text-button" onClick={()=>{setReply(m.id);document.getElementById('letter-input')?.focus();}}>回复</button>{m.own&&<button className="text-button" disabled={busy} onClick={()=>mutate('message-delete',{id:m.id})}>收回</button>}</footer>}</article>):<div className="mini-empty">第一句想说的话，会是什么呢？</div>}</div><form className="form-stack letter-compose" onSubmit={async e=>{e.preventDefault();if(await mutate('message',{text:message,parentId:reply})){setMessage('');setReply(null);setToast('你的话，已经放进信箱');}}}>{reply&&<div className="reply-to">回复 {room.messages.find(m=>m.id===reply)?.text?.slice(0,30)}<button className="text-button" onClick={()=>setReply(null)} type="button">取消</button></div>}<textarea id="letter-input" aria-label="写给对方的留言" required maxLength={1000} placeholder="今天有一件小事，想告诉你…" rows={3} value={message} onChange={e=>setMessage(e.target.value)}/><button className="primary wide" disabled={busy||!message.trim()}>把想念放进信箱 <Mail size={16}/></button></form></>}
 {modal==='photos'&&room&&<><p className="muted">{room.photos.length} / 100张回忆 · JPEG、PNG、WebP，单张最大10MB</p><div className="photo-grid">{room.photos.map(p=><article key={p.id}><div className="photo-clickable" role="button" tabIndex={0} onClick={()=>{setPhotoView(p.id);setModal(null);}} onKeyDown={e=>{if(e.target===e.currentTarget&&(e.key==='Enter'||e.key===' ')){e.preventDefault();setPhotoView(p.id);setModal(null);}}} aria-label={`查看照片${p.caption||date(p.created)}`}><PrivatePhoto src={`/api/base/photo/${p.id}`} alt={p.caption||'我们的回忆'} loading="lazy"/></div><p>{p.caption||'一起收藏的小瞬间'}</p><small>{formatPublishedTime(p.created)}</small>{p.own&&<button className="text-button" disabled={busy} onClick={async()=>{if(confirm('删除这张照片？'))await post('photo-delete',{id:p.id});}}>删除</button>}</article>)}</div><form className="form-stack" onSubmit={e=>{e.preventDefault();upload();}}><label className="file-picker"><Camera size={22}/>{photo?photo.name:'选一张今天的照片'}<input aria-label="选择照片" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setPhoto(e.target.files?.[0]||null)}/></label><input aria-label="照片说明" placeholder="为这一刻写一句话（可选）" maxLength={300} value={caption} onChange={e=>setCaption(e.target.value)}/><button className="primary wide" disabled={busy||!photo||room.photos.length>=100}>{busy?'正在收藏…':'收藏这一刻'}</button></form></>}
 {modal==='challenge'&&<form className="form-stack" onSubmit={async e=>{e.preventDefault();if(await mutate('challenge-create',{title,description,deadline})){setTitle('');setDescription('');setDeadline('');setModal(null);setChallengeFilter('custom');setTab('challenges');}}}><label>一起做什么？<input required maxLength={40} placeholder="比如：周末一起做一顿早餐" value={title} onChange={e=>setTitle(e.target.value)}/></label><label>小小的约定<textarea maxLength={300} rows={3} placeholder="想怎么完成？" value={description} onChange={e=>setDescription(e.target.value)}/></label><label>想在哪天之前完成？（可选）<input type="date" min={room?.day} value={deadline} onChange={e=>setDeadline(e.target.value)}/></label><button className="primary wide" disabled={busy}>把约定放上挑战墙</button></form>}
 {modal==='settings'&&room&&<><form className="form-stack" onSubmit={async e=>{e.preventDefault();if(await mutate('profile',{name:nick,roomName})){setModal(null);setToast('小屋信息已更新');}}}><label>你的昵称<input required maxLength={20} value={nick} onChange={e=>setNick(e.target.value)}/></label><label>小屋名字<input required maxLength={30} value={roomName} onChange={e=>setRoomName(e.target.value)}/></label><button className="primary wide" disabled={busy}>保存</button></form><div className="settings-footer"><a href={standalone?authHref:'/signout-with-chatgpt?return_to=%2F'} target="_top">退出登录</a><button className="text-button danger" onClick={()=>setModal('leave')}>离开小屋</button></div></>}
 {modal==='leave'&&<div className="form-stack"><p>离开后，你将无法访问这间小屋。共同的留言、照片和家具保留给另一位成员，进行中的游戏会结束。</p><button className="danger-button" disabled={busy} onClick={async()=>{if(await post('leave',{})){setModal(null);setTab('room');setGameOpen(false);setInviteCode('');}}}>确认离开小屋</button><button className="outline" onClick={()=>setModal('settings')}>留在这里</button></div>}
 </ModalBox>}
 {photoView&&room?.photos.some(p=>p.id===photoView)&&<ModalBox title="我们收藏的这一刻" onClose={()=>{setPhotoView(null);setModal('photos');}}><PhotoViewer id={photoView} caption={room.photos.find(p=>p.id===photoView)!.caption} created={room.photos.find(p=>p.id===photoView)!.created}/></ModalBox>}
 </div>;
}
function Empty({icon,title,text,action}:{icon:string;title:string;text:string;action:()=>void}){return <div className="empty-state"><span>{icon}</span><h3>{title}</h3><p>{text}</p><button className="outline" onClick={action}>从这里开始 <ChevronRight size={16}/></button></div>;}
function ModalBox({title,onClose,children}:{title:string;onClose:()=>void;children:ReactNode}){const ref=useRef<HTMLDivElement>(null);useEffect(()=>{const before=document.activeElement as HTMLElement|null,old=document.body.style.overflow;document.body.style.overflow='hidden';ref.current?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose();if(e.key==='Tab'){const nodes=Array.from(ref.current?.querySelectorAll<HTMLElement>('button:not(:disabled),a[href],input,textarea,select,[tabindex="0"]')||[]),first=nodes[0],last=nodes.at(-1);if(!nodes.length){e.preventDefault();return;}if(e.shiftKey&&(document.activeElement===first||document.activeElement===ref.current)){e.preventDefault();last?.focus();}else if(!e.shiftKey&&(document.activeElement===last||document.activeElement===ref.current)){e.preventDefault();first?.focus();}}};document.addEventListener('keydown',key);return()=>{document.body.style.overflow=old;document.removeEventListener('keydown',key);before?.focus();};},[]);
 return <div className="modal-backdrop" onClick={e=>{if(e.target===e.currentTarget)onClose();}}><div className="modal" role="dialog" aria-modal="true" aria-label={title} tabIndex={-1} ref={ref}><header><h2>{title}</h2><button className="icon-button" onClick={onClose} aria-label="关闭"><X size={21}/></button></header><div className="modal-content">{children}</div></div></div>;}




function cooperativeResult(s:VisibleState){if(s.id==='escape')return s.extra?.stage===3?'三道门都打开了！':'这次没能开锁，下次一起再试';if(s.id==='match')return (s.scores?.reduce((a,b)=>a+b,0)||0)>=220?'一起过关了！':'差一点过关，再试一次？';if(s.id==='draw')return '画猜完成，留下了我们的作品';return '一起完成了，真棒！';}

