'use client';
import {useEffect,useRef,useState} from 'react';
import {Pencil,Eraser,Undo2,Trash2} from 'lucide-react';
import {createStrokePublisher,acknowledgeStroke,enqueueStroke,visibleStrokes,drawingInks,strokePath,type Stroke} from '@/src/games/drawing';
import type {Action} from '@/src/games/engine';
type Props={strokes:Stroke[];legacy:(number|null)[];editable:boolean;busy:boolean;round:number;send:(a:Action)=>Promise<boolean>};
export default function DrawingPad({strokes,legacy,editable,busy,round,send}:Props){
 const [color,setColor]=useState(5),[penWidth,setPenWidth]=useState(8),[eraserWidth,setEraserWidth]=useState(28),[tool,setTool]=useState<'pen'|'eraser'>('pen'),[pending,setPending]=useState<Stroke[]>([]),[live,setLive]=useState<Stroke|null>(null),[failed,setFailed]=useState(false),[sending,setSending]=useState(false);
 const width=tool==='pen'?penWidth:eraserWidth;
 const svg=useRef<SVGSVGElement>(null),current=useRef<Stroke|null>(null),running=useRef(false),sender=useRef(send),generation=useRef(0);sender.current=send;
 const publisher=useRef(createStrokePublisher(stroke=>setPending(old=>enqueueStroke(old,stroke))));
 useEffect(()=>{publisher.current.reset();generation.current++;current.current=null;setLive(null);setPending([]);setFailed(false);},[round,editable]);
 useEffect(()=>{if(!editable||busy||failed||running.current||!pending.length)return;const stroke=pending[0],version=round,token=generation.current;running.current=true;setSending(true);void sender.current({stroke,round:version}).then(ok=>{if(generation.current!==token)return;if(ok)setPending(old=>acknowledgeStroke(old,stroke));else setFailed(true);}).finally(()=>{running.current=false;setSending(false);});},[pending,busy,failed,editable,round,sending]);
 useEffect(()=>{if(!editable)return;const timer=setInterval(()=>{const stroke=current.current;if(stroke)publisher.current.publish(stroke);},220);return()=>clearInterval(timer);},[editable,round]);
 const point=(x:number,y:number)=>{const box=svg.current!.getBoundingClientRect();return [Math.max(0,Math.min(1000,Math.round((x-box.left)/box.width*1000))),Math.max(0,Math.min(1000,Math.round((y-box.top)/box.height*1000)))];};
 const finish=()=>{const stroke=current.current;current.current=null;setLive(null);if(stroke)setPending(old=>enqueueStroke(old,stroke));};
 const visible=visibleStrokes(strokes,pending,live);
 const canEdit=editable&&!pending.length&&!live&&!busy;
 return <div className="drawing-studio">{editable&&<><div className="drawing-tools"><button aria-pressed={tool==='pen'} className={tool==='pen'?'chosen':''} onClick={()=>setTool('pen')}><Pencil size={18}/>画笔</button><button aria-pressed={tool==='eraser'} className={tool==='eraser'?'chosen':''} onClick={()=>setTool('eraser')}><Eraser size={18}/>橡皮</button><button aria-label="撤销上一笔" disabled={!canEdit||!strokes.length} onClick={()=>send({drawing:'undo',round})}><Undo2 size={18}/></button><button aria-label="清空画板" disabled={!canEdit} onClick={()=>{if(confirm('清空本轮画板？'))send({drawing:'clear',round});}}><Trash2 size={18}/></button></div><div className="drawing-palette">{drawingInks.map((ink,i)=><button key={ink} aria-label={['红色','黄色','绿色','蓝色','紫色','黑色','粉色','棕色'][i]} aria-pressed={color===i&&tool==='pen'} className={color===i&&tool==='pen'?'chosen':''} style={{background:ink}} onClick={()=>{setColor(i);setTool('pen');}}/>)}<label>粗细<select aria-label="画笔粗细" value={width} onChange={e=>(tool==='pen'?setPenWidth:setEraserWidth)(Number(e.target.value))}>{[4,8,16,28].map(v=><option key={v} value={v}>{v===4?'细':v===8?'中':v===16?'粗':'特粗'}</option>)}</select></label></div></>}
 <svg ref={svg} viewBox="0 0 1000 1000" className="freehand-board" role="img" aria-label={editable?'手绘画板':'对方的画板'} style={{touchAction:editable?'none':'auto'}} onPointerDown={e=>{if(!editable||current.current||pending.length>=12||strokes.length+pending.length>=160)return;e.currentTarget.setPointerCapture(e.pointerId);current.current={id:crypto.randomUUID(),color,width,tool,points:[point(e.clientX,e.clientY)]};setLive({...current.current});}} onPointerMove={e=>{const s=current.current;if(!s)return;const p=point(e.clientX,e.clientY),last=s.points.at(-1)!;if(Math.hypot(p[0]-last[0],p[1]-last[1])<2)return;if(s.points.length>=240){publisher.current.publish(s);current.current={...s,id:crypto.randomUUID(),points:[last,p]};setLive({...current.current});return;}s.points.push(p);setLive({...s,points:[...s.points]});}} onPointerUp={finish} onPointerCancel={finish} onLostPointerCapture={finish}>
 <rect width="1000" height="1000" fill="#fffdf6"/>{legacy.some(Boolean)&&legacy.map((c,i)=>c?<rect key={i} x={i%12*1000/12} y={Math.floor(i/12)*1000/12} width={1000/12+1} height={1000/12+1} fill={['#fffdf6','#de777b','#efc36b','#7ba78d','#7f9dbf','#343f45'][c]}/>:null)}
 {visible.map(s=><path key={s.id} d={strokePath(s.points)} stroke={s.tool==='eraser'?'#fffdf6':drawingInks[s.color]} strokeWidth={s.width} strokeLinecap="round" strokeLinejoin="round" fill="none"/>)}</svg>
 {editable&&<div className="drawing-sync" aria-live="polite">{failed?<><span>未同步的笔画已保留。</span><button className="outline" disabled={busy} onClick={()=>setFailed(false)}>重试同步</button><button className="text-button" disabled={busy||sending} onClick={()=>{setPending([]);setFailed(false);}}>放弃未同步笔画</button></>:<span>{sending||pending.length?`正在同步 · ${pending.length} 笔待保存`:'边画边同步 · 对方会持续看到新增线条'}</span>}</div>}</div>;
}
