'use client';
import {useEffect,useState} from 'react';
import DrawingPad from './DrawingPad';
import type {Action,Slot} from '@/src/games/engine';
import type {VisibleState} from './GamePlay';
const colors=['白','红','黄','绿','蓝','黑'],inks=['#fffdf6','#de777b','#efc36b','#7ba78d','#7f9dbf','#343f45'],gems=['🍓','🍋','🥝','🫐','🍇'];
type Props={state:VisibleState;slot:Slot;names:string[];busy:boolean;onAction:(a:Action)=>Promise<boolean>};
export default function ExtendedPlay({state:s,slot,names,busy,onAction}:Props){const e=s.extra!,[localNote,setLocalNote]=useState(''),[ships,setShips]=useState<number[]>([]),[vertical,setVertical]=useState(false),[text,setText]=useState(''),[statements,setStatements]=useState(['','','']),[lie,setLie]=useState(0),[selected,setSelected]=useState<number|null>(null),[answers,setAnswers]=useState<number[]>(Array(8).fill(-1)),[predictions,setPredictions]=useState<number[]>(Array(8).fill(-1));
 const turn=s.turn===slot&&!s.done&&!busy,disabled=busy||!!s.done;
 const send=async(a:Action)=>{if(await onAction(a)){setText('');setSelected(null);setLocalNote('');}};
 useEffect(()=>{setText('');setStatements(['','','']);},[e.round,e.stage]);
 const note=<p className="turn-note">{s.done?'本局结束':turn?'轮到你啦':`轮到${names[s.turn||0]}`} · {s.scores?.join(' : ')}</p>;
 if(s.id==='fleet'){const placed=!!e.counts?.[slot],both=e.counts?.every(Boolean),length=[3,2,2][ships.length===0?0:ships.length===3?1:2];return <>{!placed&&!s.done?<><p className="turn-note">布置第{ships.length===0?1:ships.length===3?2:3}艘船 · 长度{length}格</p><button className="outline" onClick={()=>setVertical(v=>!v)}>方向：{vertical?'竖直 ↓':'水平 →'}</button><div className="extra-grid six">{Array.from({length:36},(_,c)=><button key={c} disabled={disabled||ships.length===7} className={ships.includes(c)?'ship':''} onClick={()=>{const add=Array.from({length},(_,i)=>c+i*(vertical?6:1));if(add.some(v=>v>=36||ships.includes(v))||!vertical&&Math.floor(c/6)!==Math.floor(add.at(-1)!/6)){setLocalNote('这里放不下整艘船，请换个起点或方向。');return;}setLocalNote('');setShips(old=>[...old,...add]);}}> {ships.includes(c)?'🚢':'·'}</button>)}</div><p className="muted">点船头放置整艘船；三艘船不能重叠，可以相邻。</p>{localNote&&<p className="game-local-note" role="status">{localNote}</p>}<div className="extra-actions"><button className="outline" disabled={!ships.length||disabled} onClick={()=>{setShips(old=>old.slice(0,old.length===7?5:old.length===5?3:0));setLocalNote('');}}>撤回上一艘</button><button className="outline" onClick={()=>setShips([])}>重新布置</button><button className="primary" disabled={disabled||ships.length!==7} onClick={()=>send({answers:ships})}>藏好舰队</button></div></>:<><p className="turn-note">{s.done?'海战结束':!both?'等待对方布置舰队':turn?'选择对方海域，发射一次攻击':`等待${names[s.turn||0]}攻击`}</p><div className="extra-grid six">{s.board?.map((v,c)=><button key={c} disabled={!turn||!both||v!==null} className={v===1?'hit':v===0?'miss':''} aria-label={`攻击第${Math.floor(c/6)+1}行第${c%6+1}列`} onClick={()=>send({cell:c})}>{v===1?'🔥':v===0?'•':'🌊'}</button>)}</div><p className="muted">你的海域 · 🚢舰船 / 🔥被击中</p><div className="extra-grid six mini">{Array.from({length:36},(_,c)=><span key={c}>{e.shots?.[1-slot]?.includes(c)?e.clues?.includes(c)?'🔥':'•':e.clues?.includes(c)?'🚢':'·'}</span>)}</div></>}</>;}
 if(s.id==='cards'){const hand=e.hands?.[slot]||[],top=e.pile?.[0]||0,labels=['红','黄','绿','蓝'];const label=(c:number)=>`${labels[Math.floor(c/12)]} ${c%12===10?'禁行':c%12===11?'+2':c%12}`;return <>{note}<p className="muted">对方剩 {e.counts?.[1-slot]} 张 · 你剩 {hand.length} 张</p><div className="card-discard" style={{borderColor:inks[Math.floor(top/12)+1]}}>当前牌<br/><b>{label(top)}</b></div><div className="hand-cards">{hand.map((c,i)=><button key={i} disabled={!turn||Math.floor(c/12)!==Math.floor(top/12)&&c%12!==top%12} style={{borderColor:inks[Math.floor(c/12)+1]}} onClick={()=>send({choice:i})}>{label(c)}</button>)}</div><button className="outline wide" disabled={!turn} onClick={()=>send({choice:-1})}>抽一张，结束回合</button><p className="muted">相同颜色或数字才能出牌；禁行和加二都能让你继续出牌。</p></>;}
 if(s.id==='maze'){const c=e.position||0;return <>{note}<p className="muted">你看到{slot===0?'上下':'左右'}的墙，另两个方向在下方公屏询问对方，可一键发当前位置线索。钥匙 {e.keys?.length} / 2</p><div className="maze-grid">{e.clues?.map((v,i)=><span key={i} style={{borderTopColor:v&1?'#586e61':'transparent',borderRightColor:v&2?'#586e61':'transparent',borderBottomColor:v&4?'#586e61':'transparent',borderLeftColor:v&8?'#586e61':'transparent'}}>{i===c?'🧑‍🚀':[6,42].includes(i)&&!e.keys?.includes(i)?'🔑':i===48?'🚪':''}</span>)}</div><div className="direction-buttons">{['↑','→','↓','←'].map((v,i)=><button key={i} disabled={!turn} aria-label={`移动${v}`} onClick={()=>send({choice:i})}>{v}</button>)}</div><p className="muted">从左上出发，拿齐钥匙后前往右下出口。点到墙壁不会扣步。</p></>;}
 if(s.id==='escape')return <><p className="turn-note">{s.done?e.stage===3?'三道门都打开了！':'机会用完了，下一局再试':'第'+((e.stage||0)+1)+'道锁 / 3'}</p><div className="lock-hint">{e.hint}</div><p>你的线索是第{slot===0?'1、3':'2、4'}位数字；缺失的两位在对方手里，可在下方公屏发送线索。</p><p className="muted">本关还剩 {8-(e.attempts||0)} 次尝试，数字可重复，可0开头。</p><form className="digit-form" onSubmit={v=>{v.preventDefault();send({guess:text});}}><input value={text} disabled={disabled} aria-label="四位密码" inputMode="numeric" maxLength={4} onChange={v=>setText(v.target.value.replace(/\D/g,''))}/><button className="primary" disabled={disabled||text.length!==4}>一起开锁</button></form></>;
 if(s.id==='liar')return <>{note}<p className="muted">第 {Math.min(6,(e.round||0)+1)} / 6 回合。可在下方公屏提问，猜完会揭晓假话。</p>{!e.statements?.length?turn?<div className="form-stack">{statements.map((v,i)=><label key={i}>第{i+1}句话<input maxLength={80} value={v} placeholder="写下两真一假的三个故事" onChange={ev=>setStatements(old=>old.map((x,j)=>j===i?ev.target.value:x))}/></label>)}<label>其中哪句是假的？<select value={lie} onChange={v=>setLie(Number(v.target.value))}>{[0,1,2].map(i=><option key={i} value={i}>第{i+1}句</option>)}</select></label><button className="primary" disabled={disabled||statements.some(v=>!v.trim())||new Set(statements.map(v=>v.trim())).size!==3} onClick={()=>send({statements,choice:lie})}>藏好真假，交给对方猜</button></div>:<p>{s.done?'六回合完成':'等对方写下三个故事'}</p>:<div className="question-list">{e.statements.map((v,i)=><button className="outline wide" key={i} disabled={disabled||s.turn===slot} onClick={()=>send({choice:i})}>{i+1}. {v}</button>)}{s.turn===slot&&<p>你的故事已送出，等待对方选择。</p>}</div>}</>;
 if(s.id==='draw')return <><p className="turn-note">第 {Math.min(4,(e.round||0)+1)} / 4 回合 · {s.done?'画猜完成':s.turn===slot?'你画，对方在下方公屏猜':'对方画，你在下方公屏猜'}</p>{s.turn===slot&&!s.done&&<p className="draw-prompt">题目：{e.word} <small>仅你可见</small></p>}<DrawingPad strokes={e.strokes||[]} legacy={s.board||[]} editable={s.turn===slot&&!s.done} busy={busy} round={e.round||0} send={onAction}/>{s.turn===slot&&!s.done&&<button className="text-button" disabled={busy} onClick={()=>send({choice:-1,round:e.round})}>跳过这个词（揭晓答案）</button>}<p className="muted">得分 {s.scores?.join(' : ')} · 双方每回合交换角色，猜测及结果见下方公屏。</p></>;
 if(s.id==='chemistry'){if(s.done)return <div className="answer-results">{s.questions?.map((q,i)=><div key={i}><h4>{q.title}</h4>{names.map((n,p)=><p key={p}>{n}：{q.options[s.answers?.[p]?.[i]||0]}<br/>预测对方：{q.options[s.predictions?.[p]?.[i]||0]} {s.predictions?.[p]?.[i]===s.answers?.[1-p]?.[i]?'✓':'○'}</p>)}</div>)}</div>;if(s.answers?.[slot])return <p className="turn-note">你的答案已收好，等对方完成再一起揭晓。</p>;return <><div className="question-list">{s.questions?.map((q,i)=><div className="question" key={i}><small>{i+1} / 8</small><h3>{q.title}</h3>{[false,true].map(pred=><div key={String(pred)}><p>{pred?'猜猜对方的选择':'你的选择'}</p><div className="answer-options">{q.options.map((v,j)=><button key={j} disabled={disabled} className={(pred?predictions:answers)[i]===j?'chosen':''} onClick={()=>(pred?setPredictions:setAnswers)(old=>old.map((x,k)=>k===i?j:x))}>{v}</button>)}</div></div>)}</div>)}</div><button className="primary wide" disabled={disabled||answers.includes(-1)||predictions.includes(-1)} onClick={()=>send({answers,predictions})}>提交八个情境，等你揭晓</button></>;}
 if(s.id==='match')return <>{note}<p className="turn-note">共同得分 {s.scores?.reduce((a,b)=>a+b,0)} / 220 · 剩余 {e.remaining} 步</p>{s.done&&<p>{(s.scores?.reduce((a,b)=>a+b,0)||0)>=220?'一起过关了！':'这局差一点，下次试着制造连锁！'}</p>}<div className="extra-grid six candy-grid">{s.board?.map((v,i)=><button key={i} disabled={!turn} className={selected===i?'chosen':''} aria-label={`第${Math.floor(i/6)+1}行第${i%6+1}列${gems[v||0]}`} onClick={()=>{if(selected===null)setSelected(i);else if(selected===i)setSelected(null);else send({a:selected,b:i});}}>{gems[v||0]}</button>)}</div><p className="muted">选两颗相邻糖果交换。最近连锁 {e.combo} 次；无法三连的交换不扣步。</p></>;
 return null;
}