'use client';
import {useState,useEffect,useRef} from 'react';
import ExtendedPlay from './ExtendedPlay';import {useGameEffects} from './useGameEffects';
import {catalog,reversiFlips,type State,type Slot,type Action} from '@/src/games/engine';
export type VisibleState=Partial<State>&{ready:boolean[]};
type Props={state:VisibleState;slot:Slot;names:string[];busy:boolean;onAction:(a:Action)=>Promise<boolean>};
const fruits=['🍓','🍋','🍒','🥝','🍇','🍊','🍑','🫐'];
export default function GamePlay({state:s,slot,names,busy,onAction}:Props){const [selected,setSelected]=useState<number|null>(null),[digits,setDigits]=useState(''),[answers,setAnswers]=useState<number[]>([-1,-1,-1,-1,-1]),[predictions,setPredictions]=useState<number[]>([-1,-1,-1,-1,-1]),[order,setOrder]=useState([0,1,2,3,4]);const effects=useGameEffects(s);const myTurn=s.turn===slot&&!s.done&&!busy;
 const send=async(a:Action)=>{if(await onAction(a)){setDigits('');setSelected(null);}};
 if(s.extra)return <ExtendedPlay state={s} slot={slot} names={names} busy={busy} onAction={onAction}/>;
 if(['tictactoe','connect4','gomoku','reversi'].includes(s.id||'')){const width=s.id==='tictactoe'?3:s.id==='connect4'?7:s.id==='gomoku'?15:8,board=s.board||[];
 return <><p className="turn-note">{s.done?'这一局结束啦':myTurn?'轮到你啦，慢慢想':`等${names[s.turn||0]}落子`}</p>{s.id==='connect4'&&<div className="drop-buttons">{Array.from({length:7},(_,i)=><button disabled={!myTurn} aria-label={`第${i+1}列落子`} key={i} onClick={()=>send({cell:i})}>↓</button>)}</div>}<div className={`board ${s.id}`} style={{gridTemplateColumns:`repeat(${width},1fr)`}}>{board.map((value,i)=><button key={i} className={`cell ${selected===i?'selected':''}`} disabled={s.id==='connect4'||!myTurn||value!==null} aria-label={`第${Math.floor(i/width)+1}行第${i%width+1}列${value===null?'空格':value===slot?'我的棋子':'对方棋子'}`} onClick={()=>s.id==='gomoku'?setSelected(i):send({cell:i})}>{value!==null?<span key={value} className={`piece p${value} ${effects.find(e=>e.position===i)?.type==='flip'?'piece-flip':effects.some(e=>e.position===i)?'piece-place':''}`}>{s.id==='tictactoe'?(value===0?'✕':'○'):''}</span>:s.id==='reversi'&&myTurn&&reversiFlips(board,i,slot).length?<span className="legal-dot"/>:null}</button>)}</div>{s.id==='gomoku'&&selected!==null&&<div className="move-confirm"><p>第 {Math.floor(selected/15)+1} 行 · 第 {selected%15+1} 列</p><div className="direction-buttons">{[[-15,'↑'],[-1,'←'],[1,'→'],[15,'↓']].map(([n,label])=><button key={label} aria-label={`调整位置${label}`} onClick={()=>{const next=selected+Number(n);if(next>=0&&next<225&&((n!==1&&n!==-1)||Math.floor(next/15)===Math.floor(selected/15)))setSelected(next);}}>{label}</button>)}<button className="primary" disabled={busy||board[selected]!==null} onClick={()=>send({cell:selected})}>确认落子</button></div></div>}</>;}
 if(s.id==='memory')return <><p className="turn-note">{s.done?'翻牌完成':myTurn?'轮到你，翻开两张牌':`等${names[s.turn||0]}翻牌`} · {s.scores?.join(' : ')}</p><div className="memory-board">{(s.board||[]).map((v,i)=><button key={i} className={v!==null?'flipped':''} disabled={!myTurn||(s.matched||[]).includes(i)||(s.flipped||[]).includes(i)} aria-label={`第${i+1}张牌${v!==null?' '+fruits[v]:'，未翻开'}`} onClick={()=>send({cell:i})}><span key={String(v)} className={effects.some(e=>e.position===i)?'card-reveal':''}>{v===null?'✿':fruits[v]}</span></button>)}</div><p className="muted">找到一对就可以继续翻。一起慢慢记住它们。</p></>;
 if(s.id==='rps')return <><div className="rps-score">{s.scores?.[0]} <span>:</span> {s.scores?.[1]}</div><p className="turn-note">{s.done?'先赢三回合，挑战完成':s.choices?.[slot]!==null?'你已出拳，等对方揭晓':'选择你的出拳，提交后对方才会看到'}</p><div className="rps-options">{['✊','✋','✌️'].map((icon,i)=><button key={i} disabled={busy||s.done||s.choices?.[slot]!==null} onClick={()=>send({choice:i})}><span>{icon}</span>{['石头','布','剪刀'][i]}</button>)}</div>{s.rounds?.length?<div className="round-list">{s.rounds.map(([a,b],i)=><p key={i}>第{i+1}回合 <b>{['✊','✋','✌️'][a]}　{['✊','✋','✌️'][b]}</b><span>{a===b?'平局':(a-b+3)%3===1?`${names[0]}赢`:`${names[1]}赢`}</span></p>)}</div>:null}</>;
 if(s.id==='bulls'){const setSecret=!s.ready[slot],canGuess=s.ready.every(Boolean)&&myTurn;return <><p className="turn-note">{s.done?'数字谜底已经被找到':setSecret?'设置只属于你的四位数字':!s.ready.every(Boolean)?'你已设置好，等待对方':myTurn?'轮到你猜对方的数字':`等${names[s.turn||0]}猜数字`}</p>{!s.done&&(setSecret||canGuess)&&<form onSubmit={e=>{e.preventDefault();send(setSecret?{secret:digits}:{guess:digits});}} className="digit-form"><input aria-label={setSecret?'设置秘密数字':'猜测数字'} inputMode="numeric" maxLength={4} placeholder="0123" value={digits} onChange={e=>setDigits(e.target.value.replace(/\D/g,''))}/><button className="primary" disabled={busy||digits.length!==4||new Set(digits).size!==4}>{setSecret?'悄悄设置':'猜一下'}</button></form>}<p className="muted">4位数字不重复，可以0开头。A：数字和位置都对；B：数字对，位置不对。</p><div className="round-list">{s.guesses?.map((g,i)=><p key={i}><span>{names[g.slot]}</span><b>{g.guess}</b><span>{g.exact}A {g.near}B</span></p>)}</div></>;}
 if(s.id==='reflex')return <Reflex done={!!s.done} submitted={s.ready[slot]} busy={busy} onSubmit={trials=>send({trials})}/>;
 if(s.id==='puzzle')return <><p className="turn-note">{s.done?'拼好啦，这幅风景属于我们':'选两块交换位置，两个人都能操作'}</p><div className="puzzle-board">{s.tiles?.map((tile,i)=><button key={i} aria-label={`位置${i+1}，拼块${tile+1}`} className={selected===i?'selected':''} disabled={busy||s.done} onClick={()=>{if(selected===null)setSelected(i);else if(selected===i)setSelected(null);else send({a:selected,b:i});}} style={{backgroundPosition:`${(tile%3)*50}% ${Math.floor(tile/3)*50}%`}}><span>{tile+1}</span></button>)}</div><p className="muted">共同移动 {s.moves} 次 · 小编号是每块正确的位置</p></>;
 if(['quiz','predict','ranking'].includes(s.id||'')){const submitted=s.answers?.[slot]!==null;const setAnswer=(i:number,v:number,isPredict=false)=>{(isPredict?setPredictions:setAnswers)(old=>old.map((x,j)=>j===i?v:x));};
 if(s.done)return <div className="answer-results">{s.id==='ranking'?<>{names.map((name,p)=><div key={p}><h4>{name}的心动顺序</h4>{s.answers?.[p]?.map((v,i)=><p key={i}>{i+1}. {s.questions?.[0].options[v]}</p>)}</div>)}</>:s.questions?.map((q,i)=><div key={i}><h4>{q.title}</h4>{names.map((name,p)=><p key={p}>{name}：{q.options[s.answers?.[p]?.[i]||0]}{s.id==='predict'?` · 猜对方：${q.options[s.predictions?.[p]?.[i]||0]}`:''}</p>)}</div>)}</div>;
 if(submitted)return <div className="empty-state"><span>💌</span><h3>答案已经悄悄收好</h3><p>等对方完成，就能一起揭晓。可以先去小屋坐坐。</p></div>;
 if(s.id==='ranking'){const options=s.questions?.[0].options||[];return <><p className="turn-note">最想一起做的，排在最前面</p><div className="ranking-list">{order.map((v,i)=><div key={v}><b>{i+1}</b><span>{options[v]}</span><button aria-label={`${options[v]}向上移`} disabled={!i||busy} onClick={()=>setOrder(old=>{const a=[...old];[a[i],a[i-1]]=[a[i-1],a[i]];return a;})}>↑</button><button aria-label={`${options[v]}向下移`} disabled={i===4||busy} onClick={()=>setOrder(old=>{const a=[...old];[a[i],a[i+1]]=[a[i+1],a[i]];return a;})}>↓</button></div>)}</div><button className="primary wide" disabled={busy} onClick={()=>send({answers:order})}>藏好我的心动顺序</button></>;}
 return <><div className="question-list">{s.questions?.map((q,i)=><div className="question" key={i}><small>0{i+1} / 05</small><h3>{q.title}</h3><div className="answer-options">{q.options.map((o,v)=><button key={v} className={answers[i]===v?'chosen':''} disabled={busy} onClick={()=>setAnswer(i,v)}>{o}</button>)}</div>{s.id==='predict'&&<><p>猜猜对方会选什么？</p><div className="answer-options prediction">{q.options.map((o,v)=><button key={v} className={predictions[i]===v?'chosen':''} disabled={busy} onClick={()=>setAnswer(i,v,true)}>{o}</button>)}</div></>}</div>)}</div><button className="primary wide" disabled={busy||answers.some(x=>x<0)||(s.id==='predict'&&predictions.some(x=>x<0))} onClick={()=>send({answers,predictions})}>藏好答案，等你揭晓</button></>;}
 return null;
}
function Reflex({done,submitted,busy,onSubmit}:{done:boolean;submitted:boolean;busy:boolean;onSubmit:(values:number[])=>void}){const [phase,setPhase]=useState<'idle'|'waiting'|'green'>('idle'),[trials,setTrials]=useState<number[]>([]),[note,setNote]=useState('准备好，就开始吧');const timer=useRef<ReturnType<typeof setTimeout>|null>(null),started=useRef(0);
 useEffect(()=>{const hidden=()=>{if(document.hidden){if(timer.current)clearTimeout(timer.current);setPhase('idle');setNote('刚才那次已取消，回来后重新开始');}};document.addEventListener('visibilitychange',hidden);return()=>{if(timer.current)clearTimeout(timer.current);document.removeEventListener('visibilitychange',hidden);};},[]);
 const click=()=>{if(phase==='idle'){setNote('等它变绿……先不要点');setPhase('waiting');timer.current=setTimeout(()=>{started.current=performance.now();setPhase('green');setNote('现在！');},1200+Math.random()*2500);}else{if(timer.current)clearTimeout(timer.current);const value=phase==='waiting'?2000:Math.min(10000,Math.round(performance.now()-started.current));setTrials(a=>[...a,value]);setPhase('idle');setNote(phase==='waiting'?'抢跑啦，这次记2000ms':`${value} ms，接得不错！`);}};
 if(done||submitted)return <div className="empty-state"><span>⚡</span><h3>计时已收好</h3><p>两人都完成5次后比较中位成绩。</p></div>;
 return <div className="reflex"><p>{trials.length} / 5 次</p><button className={`reflex-button ${phase}`} disabled={busy||trials.length===5} onClick={click}>{phase==='green'?'快点！':phase==='waiting'?'等等…':'点我开始'}</button><p aria-live="polite">{note}</p><div className="trial-pills">{trials.map((v,i)=><span key={i}>{v} ms</span>)}</div>{trials.length===5&&<button className="primary wide" disabled={busy} onClick={()=>onSubmit(trials)}>提交我的成绩</button>}</div>;
}


