'use client';
import {useState} from 'react';
export default function KeyLogin({initialKey}:{initialKey:string}){
 const [key,setKey]=useState(initialKey),[input,setInput]=useState(''),[login,setLogin]=useState(false),[busy,setBusy]=useState(false),[saved,setSaved]=useState(false),[error,setError]=useState('');
 async function submit(action:'create'|'login'|'logout'){setBusy(true);setError('');try{const res=await fetch('/api/key',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,key:input})}),data=await res.json() as {error?:string;key:string};if(!res.ok)throw Error(data.error||'暂时没连上');if(action==='create'){setKey(data.key);setLogin(false);setSaved(false);}else window.location.href='/';}catch(e){setError(e instanceof Error?e.message:'暂时没连上');}finally{setBusy(false);}}
 return <main className="key-login"><a className="text-button" href="/">← 回到小屋</a><section className="key-card"><span className="key-illustration">🗝️</span><p className="eyebrow">A KEY TO OUR LITTLE HOME</p><h1>{key&&!login?'收好你的小屋钥匙':'给自己一把小屋钥匙'}</h1><p>两个人，各有一把私人钥匙。小屋邀请码用来配对，私人钥匙用来登录。</p>{error&&<p role="alert" className="key-error">{error}</p>}
 {key&&!login?<><p>请复制并保存到密码管理器或安全的位置。换手机时，用这把钥匙找回你的小屋。</p><code className="private-key">{key.match(/.{1,8}/g)?.join('-')}</code><p className="key-hint">不要把私人钥匙发给对方，也不要发在公开聊天里。丢失后无法替你找回。</p><button className="outline" onClick={async()=>{try{await navigator.clipboard.writeText(key);setError('钥匙已复制，请保存好');}catch{setError('请长按钥匙复制保存');}}}>复制私人钥匙</button><label className="key-saved"><input type="checkbox" checked={saved} onChange={e=>setSaved(e.target.checked)}/>我已安全保存这把钥匙</label><a aria-disabled={!saved} className={'primary'+(!saved?' disabled':'')} href={saved?'/':undefined}>进入我的小屋</a><button className="text-button" onClick={()=>setLogin(true)}>使用另一把钥匙登录</button><button className="text-button" disabled={busy} onClick={()=>submit('logout')}>退出当前登录</button></>:login?<form onSubmit={e=>{e.preventDefault();submit('login');}}><label htmlFor="private-key">我的私人钥匙</label><textarea id="private-key" autoComplete="off" spellCheck={false} value={input} onChange={e=>setInput(e.target.value)} placeholder="粘贴保存的64位钥匙" required/><button className="primary" disabled={busy||!input.trim()}>{busy?'正在开门…':'打开我的小屋'}</button><button type="button" className="text-button" onClick={()=>setLogin(false)}>返回</button></form>:<><button className="primary" disabled={busy} onClick={()=>submit('create')}>{busy?'正在准备…':'生成我的私人钥匙'}</button><button className="outline" onClick={()=>setLogin(true)}>我已经有钥匙</button><p className="key-hint">无需邮箱或付款信息。请两人分别在自己的手机生成钥匙。</p></>}
 </section></main>;
}
