'use client';
import {useEffect,useRef,useState} from 'react';
import {createPhotoTap} from '@/src/photo-tap';
import {privatePhotos} from '@/src/photo-cache';
export default function PrivatePhoto({src,alt,className,loading,download=false,onDoubleClick}:{src:string;alt:string;className?:string;loading?:'lazy';download?:boolean;onDoubleClick?:()=>void}){const [url,setUrl]=useState(''),[mime,setMime]=useState('image/jpeg'),[error,setError]=useState(''),[retry,setRetry]=useState(0),[visible,setVisible]=useState(loading!=='lazy'),ref=useRef<HTMLDivElement>(null),taps=useRef(createPhotoTap()),lastZoom=useRef(0);
 const zoom=()=>{if(Date.now()-lastZoom.current<350)return;lastZoom.current=Date.now();onDoubleClick?.();};
 useEffect(()=>{if(loading!=='lazy'||visible)return;if(!('IntersectionObserver' in window)){setVisible(true);return;}const observer=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting)){setVisible(true);observer.disconnect();}},{rootMargin:'180px'});if(ref.current)observer.observe(ref.current);return()=>observer.disconnect();},[loading,visible]);
 useEffect(()=>{if(!visible)return;let disposed=false,objectUrl='';setError('');setUrl('');privatePhotos.load(src).then(blob=>{if(!disposed){objectUrl=URL.createObjectURL(blob);setMime(blob.type);setUrl(objectUrl);}}).catch(e=>{if(!disposed)setError(e instanceof Error?e.message:'照片加载失败');});return()=>{disposed=true;if(objectUrl)URL.revokeObjectURL(objectUrl);};},[src,retry,visible]);
 return <div ref={ref} className={`private-photo ${download?'photo-download':''}`}>{url?<><img src={url} alt={alt} className={className} decoding="async" onDoubleClick={onDoubleClick?zoom:undefined} onTouchStart={e=>{const p=e.touches[0];if(p)taps.current.start(p.clientX,p.clientY,e.touches.length);}} onTouchMove={e=>{const p=e.touches[0];if(p)taps.current.move(p.clientX,p.clientY,e.touches.length);}} onTouchEnd={e=>{if(onDoubleClick&&taps.current.end(Date.now())){e.preventDefault();zoom();}}} onError={()=>{setUrl('');setError('照片无法显示，请重试');}}/>{download&&<a className="outline photo-save" href={url} download={mime==='image/png'?'小满-收藏照片.png':'小满-收藏照片.jpg'}>保存照片</a>}</>:<div className="photo-placeholder" role="status">{error?<><span>{error}</span><button type="button" className="text-button" onClick={ev=>{ev.stopPropagation();setRetry(n=>n+1);}}>重新加载</button></>:<span>照片加载中…</span>}</div>}</div>;
}
