import assert from 'node:assert/strict';import {PNG} from 'pngjs';import {reversiFlips,catalog} from '../src/games/engine.ts';
const origin='http://127.0.0.1:5173',suffix=crypto.randomUUID().slice(0,8),cookies=[0,1,2].map(i=>`__sites_local_auth=1; __sites_test_member=qa${i}_${suffix}`);
async function api(p,path,body,headers={}){const res=await fetch(origin+'/api/base/'+path,{method:body===undefined?'GET':'POST',headers:{Cookie:cookies[p],...(body===undefined?{}:{Origin:origin,'Content-Type':'application/json'}),...headers},body:body===undefined?undefined:JSON.stringify(body)});const data=await res.json();if(!res.ok)throw Object.assign(Error(data.error),{status:res.status});return data;}
const mine=p=>api(p,'mine');async function cmd(p,op,payload={},requestId=crypto.randomUUID()){const m=await mine(p);return api(p,'action',{op,payload,version:m.version,requestId});}
const created=await api(0,'create',{nick:'测试兔兔',name:'双人验收小屋'}),joined=await api(1,'join',{nick:'测试狐狐',code:created.inviteCode});assert.equal((await mine(1)).room,null);await api(0,'confirm',{joinId:joined.joinId});assert.equal((await mine(1)).room.members[0].name,'测试兔兔');assert.equal((await mine(2)).room,null);console.log('PASS actual server pair and isolation');
const mid=crypto.randomUUID(),v=(await mine(0)).version;await api(0,'action',{op:'message',payload:{text:'测试留言'},version:v,requestId:mid});await api(0,'action',{op:'message',payload:{text:'测试留言'},version:v,requestId:mid});assert.equal((await mine(1)).room.messages.length,1);await cmd(1,'message',{text:'收到！',parentId:(await mine(1)).room.messages[0].id});await cmd(1,'message-read');assert.equal((await mine(0)).room.messages[0].read[1],true);console.log('PASS message reply, read and retry');
for(const g of catalog){await cmd(0,'game-create',{id:g.id});await cmd(1,'game-accept');let m=await mine(0),s=m.room.game.state;
 if(g.id==='tictactoe')for(const[p,cell]of [[0,0],[1,3],[0,1],[1,4],[0,2]])await cmd(p,'game-action',{cell});
 if(g.id==='connect4'){for(let i=0;i<3;i++){await cmd(0,'game-action',{cell:0});await cmd(1,'game-action',{cell:1});}await cmd(0,'game-action',{cell:0});}
 if(g.id==='gomoku'){for(let i=0;i<4;i++){await cmd(0,'game-action',{cell:i});await cmd(1,'game-action',{cell:30+i});}await cmd(0,'game-action',{cell:4});}
 if(g.id==='reversi'){for(let n=0;n<64;n++){s=(await mine(0)).room.game.state;if(s.done)break;const cell=s.board.findIndex((_,i)=>reversiFlips(s.board,i,s.turn).length);assert.ok(cell>=0);await cmd(s.turn,'game-action',{cell});}}
 if(g.id==='rps')for(let i=0;i<3;i++){await cmd(0,'game-action',{choice:0});assert.equal((await mine(1)).room.game.state.choices[0],null);await cmd(1,'game-action',{choice:2});}
 if(g.id==='memory'){const known=new Map();for(let n=0;n<180;n++){s=(await mine(0)).room.game.state;if(s.done)break;s.board.forEach((v,i)=>{if(v!==null)known.set(i,v);});const remaining=Array.from({length:16},(_,i)=>i).filter(i=>!s.matched.includes(i)&&!s.flipped.includes(i));let cell;
  if(s.flipped.length){const first=s.flipped[0],value=s.board[first];cell=remaining.find(i=>known.get(i)===value);}
  else{cell=remaining.find(i=>known.has(i)&&remaining.some(j=>j!==i&&known.get(j)===known.get(i)));}
  cell??=remaining.find(i=>!known.has(i))??remaining[0];await cmd(s.turn,'game-action',{cell});s=(await mine(0)).room.game.state;s.board.forEach((v,i)=>{if(v!==null)known.set(i,v);});}}
 if(g.id==='bulls'){await cmd(0,'game-action',{secret:'0123'});assert.equal((await mine(1)).room.game.state.secrets,undefined);await cmd(1,'game-action',{secret:'4567'});await cmd(0,'game-action',{guess:'4567'});await cmd(1,'game-action',{guess:'0123'});}
 if(['quiz','predict','ranking'].includes(g.id)){const answers=g.id==='ranking'?[0,1,2,3,4]:[0,0,0,0,0];await cmd(0,'game-action',{answers,predictions:[0,0,0,0,0]});assert.equal((await mine(1)).room.game.state.answers[0],null);await cmd(1,'game-action',{answers,predictions:[0,0,0,0,0]});}
 if(g.id==='reflex'){await cmd(0,'game-action',{trials:[200,250,300,2000,210]});await cmd(1,'game-action',{trials:[300,350,400,2000,310]});}
 if(g.id==='puzzle')for(let i=0;i<9;i++){s=(await mine(0)).room.game.state;if(s.done)break;if(s.tiles[i]!==i)await cmd(i%2,'game-action',{a:i,b:s.tiles.indexOf(i)});}
 m=await mine(0);assert.equal(m.room.game.state.done,true,`${g.id} finished`);assert.equal(m.room.game.status,'finished');assert.ok(m.room.history.some(h=>h.gameId===g.id));console.log('PASS complete actual server',g.id);
}
assert.equal((await mine(0)).room.balance,50);await cmd(0,'challenge-create',{title:'测试共同挑战',description:'两人确认',deadline:''});const cid=(await mine(0)).room.challenges.at(-1).id;await cmd(0,'challenge-complete',{id:cid});await cmd(1,'challenge-complete',{id:cid});assert.equal((await mine(0)).room.balance,50);const before=await mine(0),req=p=>api(p,'action',{op:'buy',payload:{id:p===0?'cushion':'lamp'},version:before.version,requestId:crypto.randomUUID()});const purchases=await Promise.allSettled([req(0),req(1)]);assert.equal(purchases.filter(r=>r.status==='fulfilled').length,1);assert.equal((await mine(0)).room.balance,10);console.log('PASS reward limit and concurrent purchase');
const png=new PNG({width:20,height:20});png.data.fill(255);const photo=await fetch(origin+'/api/base/photo',{method:'POST',headers:{Origin:origin,Cookie:cookies[0],'Content-Type':'image/png','X-Photo-Caption':encodeURIComponent('测试照片')},body:PNG.sync.write(png)});assert.equal(photo.status,200,await photo.clone().text());const photoData=await photo.json();const good=await fetch(origin+'/api/base/photo/'+photoData.id,{headers:{Cookie:cookies[1]}}),bad=await fetch(origin+'/api/base/photo/'+photoData.id,{headers:{Cookie:cookies[2]}});assert.equal(good.status,200);assert.equal(bad.status,403);assert.equal(good.headers.get('content-type'),'image/png');console.log('PASS R2 photo persistence and authorization');
const cross=await fetch(origin+'/api/base/action',{method:'POST',headers:{Origin:'https://evil.example',Cookie:cookies[0],'Content-Type':'application/json'},body:'{}'});assert.equal(cross.status,403);await api(1,'leave',{});assert.equal((await mine(1)).room,null);console.log('PASS foreign origin rejected and former member revoked');console.log('ALL INTEGRATION CHECKS PASSED (local test identities, not physical phones)');
