import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';
import {BaseStore} from '../src/server/store.ts';
function db(){const sql=new DatabaseSync(':memory:');sql.exec('CREATE TABLE rooms(id TEXT PRIMARY KEY,data TEXT NOT NULL,version INTEGER NOT NULL,invite_hash TEXT UNIQUE);CREATE TABLE members(user_id TEXT PRIMARY KEY,room_id TEXT NOT NULL,slot INTEGER NOT NULL,UNIQUE(room_id,slot));');return {prepare(q){let params=[];return {bind(...p){params=p;return this;},async first(){return sql.prepare(q).get(...params)||null;},async run(){return {meta:{changes:Number(sql.prepare(q).run(...params).changes)}};},async all(){return {results:sql.prepare(q).all(...params)};},_run(){return {meta:{changes:Number(sql.prepare(q).run(...params).changes)}};}};},async batch(stmts){sql.exec('BEGIN');try{const results=stmts.map(s=>s._run());sql.exec('COMMIT');return results;}catch(e){sql.exec('ROLLBACK');throw e;}}};}
async function pair(){const d=db(),s=new BaseStore(d),a={userId:'a'},b={userId:'b'};const x=await s.create(a,'阿栗','小屋');const j=await s.join(b,x.inviteCode,'小桃');await s.confirm(a,j.joinId);return {d,s,a,b};}
test('paired persistence and strangers cannot read room',async()=>{const {d,s,a}=await pair();const mine=await s.mine(a);assert.equal(mine.room.members[1].name,'小桃');const fresh=new BaseStore(d);assert.equal((await fresh.mine(a)).room.name,'小屋');assert.equal((await s.mine({userId:'c'})).room,null);await assert.rejects(()=>s.mutate({userId:'c'},'message',{text:'x'},'r1',0));});
test('joining requires confirmation and second acceptance cannot overfill',async()=>{const s=new BaseStore(db()),a={userId:'a'};const x=await s.create(a,'a','room');const j1=await s.join({userId:'b'},x.inviteCode,'b'),j2=await s.join({userId:'c'},x.inviteCode,'c');assert.equal((await s.mine({userId:'b'})).room,null);const results=await Promise.allSettled([s.confirm(a,j1.joinId),s.confirm(a,j2.joinId)]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal((await s.mine(a)).room.members.filter(Boolean).length,2);});
test('repeated request does not duplicate message, stale version conflicts',async()=>{const {s,a}=await pair();const v=(await s.mine(a)).version;await s.mutate(a,'message',{text:'hello'},'unique-id-1',v);await s.mutate(a,'message',{text:'hello'},'unique-id-1',v);assert.equal((await s.mine(a)).room.messages.length,1);await assert.rejects(()=>s.mutate(a,'message',{text:'stale'},'unique-id-2',v),e=>e.status===409);});
test('concurrent writes cannot overspend and leave revokes old access',async()=>{const {s,a,b}=await pair();const v=(await s.mine(a)).version;const rs=await Promise.allSettled([s.mutate(a,'profile',{name:'a1'},'race-id-a',v),s.mutate(b,'profile',{name:'b1'},'race-id-b',v)]);assert.equal(rs.filter(r=>r.status==='fulfilled').length,1);await s.leave(b);assert.equal((await s.mine(b)).room,null);await assert.rejects(()=>s.mutate(b,'message',{text:'old'},'leave-id',v));});
test('revoked and expired invitation is rejected',async()=>{const s=new BaseStore(db()),a={userId:'a'};const x=await s.create(a,'a','room');await s.renew(a);await assert.rejects(()=>s.join({userId:'b'},x.inviteCode,'b'));const s2=new BaseStore(db(),()=>0),y=await s2.create(a,'a','room');s2.now=()=>86400001;await assert.rejects(()=>s2.join({userId:'b'},y.inviteCode,'b'));});
test('owner leaves, remaining member retains history and new invite works',async()=>{const {s,a,b}=await pair();await s.mutate(a,'message',{text:'原创建者留言'},'original-author', (await s.mine(a)).version);const photo=await s.addPhoto(a,'photo.png','原创建者照片');await s.leave(a);const m=await s.mine(b);assert.equal(m.room.slot,0);assert.equal(m.room.messages.length,1);const invite=await s.renew(b),c={userId:'c'},join=await s.join(c,invite.inviteCode,'新成员');await s.confirm(b,join.joinId);await assert.rejects(()=>s.removePhoto(c,photo.id));const current=await s.mine(c);await assert.rejects(()=>s.mutate(c,'message-delete',{id:current.room.messages[0].id},'new-author-delete',current.version));});
test('concurrent photo inserts enforce 100 limit',async()=>{const {s,a,b}=await pair();for(let i=0;i<99;i++)await s.addPhoto(a,'p'+i,'');const results=await Promise.allSettled([s.addPhoto(a,'pa',''),s.addPhoto(b,'pb','')]);assert.equal(results.filter(x=>x.status==='fulfilled').length,1);assert.equal((await s.mine(a)).room.photos.length,100);});

