import {permittedOrigin} from '@/src/server/origin';
import {freePhoto} from '@/src/server/free-photo';
import {freeJPEG} from '@/src/server/free-jpeg';
import {savePhoto,loadPhoto,deletePhoto} from '@/src/server/photo-storage';
import {env} from 'cloudflare:workers';
import {getChatGPTUser} from '../../../chatgpt-auth';
import {BaseStore,AppError} from '@/src/server/store';
import {normalizePNG} from '@/src/server/media';
export const dynamic='force-dynamic';
async function setup(){const user=await getChatGPTUser();if(!user)throw new AppError('请先登录，再回到小屋',401);if(!env.DB)throw new AppError('小屋存档暂时无法连接，请稍后重试',503);return {actor:{userId:user.userId},store:new BaseStore(env.DB)};}
async function bytes(request:Request,max:number){if(Number(request.headers.get('content-length'))>max)throw new AppError('内容太大了');if(!request.body)return new Uint8Array();const reader=request.body.getReader(),chunks:Uint8Array[]=[];let size=0;try{while(true){const x=await reader.read();if(x.done)break;size+=x.value.length;if(size>max)throw new AppError('内容太大了');chunks.push(x.value);}}finally{await reader.cancel();}const out=new Uint8Array(size);let offset=0;for(const c of chunks){out.set(c,offset);offset+=c.length;}return out;}
function error(e:unknown){if(!(e instanceof AppError))console.error('base-api',e instanceof Error?e.message:'Unknown');return Response.json({error:e instanceof Error&&e.message.length<150?e.message:'保存失败，请稍后再试'},{status:e instanceof AppError?e.status:400,headers:{'Cache-Control':'no-store'}});}
export async function GET(request:Request){try{const {actor,store}=await setup();const parts=new URL(request.url).pathname.split('/').filter(Boolean),action=parts[2];if(action==='photo'){const photo=await store.photo(actor,parts[3]);const object=await loadPhoto(env.DB!,env.BUCKET,photo.key);if(!object)throw new AppError('照片不存在',404);return new Response(object,{headers:{'Content-Type':photo.key.endsWith('.jpg')?'image/jpeg':'image/png','Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}});}
 const mine=await store.mine(actor),etag=`"${mine.roomId}:${mine.version}:${mine.room?.slot}:${mine.room?.day}:${mine.room?.game?.status}"`;if(mine.room&&request.headers.get('if-none-match')===etag)return new Response(null,{status:304,headers:{ETag:etag,'Cache-Control':'private, no-cache'}});return Response.json(mine,{headers:{ETag:etag,'Cache-Control':'private, no-cache'}});
 }catch(e){return error(e);}}
export async function POST(request:Request){try{const origin=request.headers.get('origin');if(!permittedOrigin(request,(env as {PUBLIC_ORIGINS?:string}).PUBLIC_ORIGINS))throw new AppError('请从小屋页面操作',403);const {actor,store}=await setup();const path=new URL(request.url).pathname.split('/').filter(Boolean)[2];
 if(path==='photo'){const mime=request.headers.get('content-type'),jpeg=mime==='image/jpeg'&&!env.BUCKET;if(mime!=='image/png'&&!jpeg)throw new AppError('请通过相册选择照片');const encoded=request.headers.get('x-photo-caption')||'';let caption='';try{caption=decodeURIComponent(encoded);}catch{throw new AppError('照片说明无效');}const input=await bytes(request,env.BUCKET?10*1024*1024:1024*1024),data=env.BUCKET?normalizePNG(input):jpeg?freeJPEG(input):freePhoto(input),key=`photos/${crypto.randomUUID()}.${jpeg?'jpg':'png'}`;await savePhoto(env.DB!,env.BUCKET,key,data);try{return Response.json(await store.addPhoto(actor,key,caption));}catch(e){await deletePhoto(env.DB!,env.BUCKET,key);throw e;}}
 let b:Record<string,unknown>;try{b=JSON.parse(new TextDecoder().decode(await bytes(request,32000)));}catch{throw new AppError('操作内容无效');}if(!b||typeof b!=='object'||Array.isArray(b))throw new AppError('操作内容无效');let result:unknown;
 switch(path){case 'create':result=await store.create(actor,b.nick as string,b.name as string);break;case 'join':result=await store.join(actor,b.code as string,b.nick as string);break;case 'confirm':result=await store.confirm(actor,b.joinId as string);break;case 'renew':result=await store.renew(actor);break;case 'leave':result=await store.leave(actor);break;case 'photo-delete':{const key=await store.removePhoto(actor,b.id as string);await deletePhoto(env.DB!,env.BUCKET,key);result={ok:true};break;}case 'action':result=await store.mutate(actor,b.op as string,(b.payload||{}) as Record<string,unknown>,b.requestId as string,b.version as number);break;default:throw new AppError('找不到这个操作',404);}
 return Response.json(result,{headers:{'Cache-Control':'no-store'}});
 }catch(e){return error(e);}}
