import {BaseStore} from '../src/server/store.ts';
import {snapshot,type Room} from '../src/server/model.ts';
import {TicketVault,memberEpoch,connectionPresence,allowPacket,type TicketIdentity} from '../src/realtime/room-policy.ts';
import {parseClientMessage,drawingEpoch,type ServerMessage} from '../src/realtime/protocol.ts';
import {applyPreview,type PreviewLayer} from '../src/realtime/reducer.ts';
type Env={DB:D1Database};
type Connection=TicketIdentity&{connectionId:string;visible:boolean;lastSeen:number;rate:{since:number;count:number}};
export class RoomRealtime{
 private ctx:DurableObjectState;private env:Env;private vault:TicketVault;private roomId='';private loaded:Promise<void>;
 private current:{room:Room;version:number;epoch:string;at:number}|null=null;
 private layer:PreviewLayer={epoch:'',strokes:{},gaps:[]};
 constructor(ctx:DurableObjectState,env:Env){this.ctx=ctx;this.env=env;this.vault=new TicketVault(ctx.storage);this.loaded=ctx.blockConcurrencyWhile(async()=>{this.roomId=await ctx.storage.get<string>('roomId')||'';});ctx.setWebSocketAutoResponse(new WebSocketRequestResponsePair('ping','pong'));}
 private async read(force=false){await this.loaded;if(!this.roomId)throw Error('Unknown room');if(!force&&this.current&&Date.now()-this.current.at<1000)return this.current;const row=await new BaseStore(this.env.DB).raw(this.roomId),room=JSON.parse(row.data) as Room;this.current={room,version:row.version,epoch:await memberEpoch(room.members),at:Date.now()};const epoch=drawingEpoch(room.game);if(this.layer.epoch!==epoch){this.layer={epoch,strokes:{},gaps:[]};this.broadcast({v:1,type:'preview-reset',gameEpoch:epoch});}const saved=room.game?.state.extra?.strokes||[];for(const stroke of saved){if((this.layer.strokes[stroke.id]?.points.length||0)<=stroke.points.length)delete this.layer.strokes[stroke.id];}return this.current;}
 private authorized(c:Connection){return !!this.current&&c.epoch===this.current.epoch&&this.current.room.members[c.slot]?.id===c.userId;}
 private send(ws:WebSocket,message:ServerMessage){try{ws.send(JSON.stringify(message));}catch{try{ws.close(1011,'Connection interrupted');}catch{}}}
 private broadcast(message:ServerMessage){for(const ws of this.ctx.getWebSockets()){const c=ws.deserializeAttachment() as Connection;if(c&&this.authorized(c))this.send(ws,message);}}
 private presence(){return connectionPresence(this.ctx.getWebSockets().map(ws=>{const c=ws.deserializeAttachment() as Connection,t=this.ctx.getWebSocketAutoResponseTimestamp(ws)?.getTime()||0;return {...c,lastSeen:Math.max(c.lastSeen,t)};}).filter(c=>this.authorized(c)),Date.now());}
 private async refresh(){const current=await this.read(true);for(const ws of this.ctx.getWebSockets()){const c=ws.deserializeAttachment() as Connection;if(!c||!this.authorized(c)){ws.close(1008,'Membership changed');continue;}this.send(ws,{v:1,type:'snapshot',epoch:current.epoch,snapshot:{roomId:this.roomId,version:current.version,room:snapshot(current.room,c.slot,Date.now()),pending:null}});}this.broadcast({v:1,type:'presence',slots:this.presence()});}
 async fetch(request:Request){await this.loaded;const url=new URL(request.url);try{
  if(url.pathname==='/ticket'&&request.method==='POST'){const identity=await request.json() as TicketIdentity;if(!identity.roomId||!identity.userId||!identity.origin||![0,1].includes(identity.slot))return new Response('Invalid identity',{status:400});if(this.roomId&&this.roomId!==identity.roomId)return new Response('Wrong room',{status:403});this.roomId=identity.roomId;await this.ctx.storage.put('roomId',this.roomId);const current=await this.read(true);if(identity.epoch!==current.epoch||current.room.members[identity.slot]?.id!==identity.userId)return new Response('Membership changed',{status:403});const ticket=await this.vault.issue(identity);await this.ctx.storage.setAlarm(Date.now()+45000);return Response.json({ticket,expires:Date.now()+60000});}
  if(url.pathname==='/publish'||url.pathname==='/revoke'){if(!this.roomId){const body=await request.json() as {roomId:string};this.roomId=body.roomId;await this.ctx.storage.put('roomId',this.roomId);}await this.refresh();return Response.json({ok:true});}
  if(url.pathname==='/connect'&&request.headers.get('Upgrade')?.toLowerCase()==='websocket'){
   // Consume atomically: two simultaneous upgrades cannot use one ticket.
   const result=await this.ctx.blockConcurrencyWhile(()=>this.vault.consume(url.searchParams.get('ticket')||'',request.headers.get('Origin')||''));if(!result.ok)return new Response('Invalid connection ticket',{status:403});const current=await this.read(true),identity=result.identity;if(identity.roomId!==this.roomId||identity.epoch!==current.epoch||current.room.members[identity.slot]?.id!==identity.userId)return new Response('Membership changed',{status:403});
   if(this.ctx.getWebSockets().filter(ws=>(ws.deserializeAttachment() as Connection)?.userId===identity.userId).length>=4)return new Response('Too many connections',{status:429});
   const pair=new WebSocketPair(),client=pair[0],server=pair[1],c:Connection={...identity,connectionId:crypto.randomUUID(),visible:true,lastSeen:Date.now(),rate:{since:Date.now(),count:0}};server.serializeAttachment(c);this.ctx.acceptWebSocket(server);
   this.send(server,{v:1,type:'hello',connectionId:c.connectionId,epoch:current.epoch,snapshot:{roomId:this.roomId,version:current.version,room:snapshot(current.room,c.slot,Date.now()),pending:null},presence:this.presence()});for(const stroke of Object.values(this.layer.strokes))this.send(server,{v:1,type:'preview-full',gameEpoch:this.layer.epoch,stroke});this.broadcast({v:1,type:'presence',slots:this.presence()});await this.ctx.storage.setAlarm(Date.now()+45000);return new Response(null,{status:101,webSocket:client});
  }return new Response('Not found',{status:404});
 }catch{return new Response('Realtime temporarily unavailable',{status:503});}}
 async webSocketMessage(ws:WebSocket,raw:string|ArrayBuffer){const c=ws.deserializeAttachment() as Connection;if(!c||typeof raw!=='string'){ws.close(1008,'Invalid packet');return;}try{const m=parseClientMessage(raw);if(!allowPacket(c.rate,Date.now())){ws.close(1008,'Rate limited');return;}c.lastSeen=Date.now();ws.serializeAttachment(c);const current=await this.read();if(!this.authorized(c)){ws.close(1008,'Membership changed');return;}
  if(m.type==='visibility'){c.visible=m.visible;ws.serializeAttachment(c);this.broadcast({v:1,type:'presence',slots:this.presence()});return;}
  if(m.type==='version-check'){if(m.version!==current.version)await this.refresh();return;}
  const game=current.room.game;if(!game||game.status!=='active'||game.state.id!=='draw'||m.gameId!==game.id||m.gameEpoch!==drawingEpoch(game))return;
  if(m.type==='preview-resync'){const stroke=this.layer.strokes[m.strokeId];if(stroke)this.send(ws,{v:1,type:'preview-full',gameEpoch:this.layer.epoch,stroke});return;}
  if(game.state.turn!==c.slot)return;const extra=game.state.extra!,saved=extra.strokes?.find(s=>s.id===m.strokeId);if(!saved&&extra.strokeIds?.includes(m.strokeId))return;if(Object.keys(this.layer.strokes).length>=160&&!this.layer.strokes[m.strokeId])return;
  if(saved&&!this.layer.strokes[m.strokeId])this.layer.strokes[m.strokeId]={...saved,seq:0};const next=applyPreview(this.layer,m);if(next.gaps.includes(m.strokeId)){this.layer={epoch:this.layer.epoch,strokes:{},gaps:[]};this.broadcast({v:1,type:'preview-reset',gameEpoch:this.layer.epoch});return;}this.layer=next;for(const peer of this.ctx.getWebSockets()){const p=peer.deserializeAttachment() as Connection;if(peer!==ws&&this.authorized(p))this.send(peer,m);}
 }catch{ws.close(1008,'Invalid packet');}}
 async webSocketClose(ws:WebSocket){try{ws.close();}catch{}await this.read(true);this.broadcast({v:1,type:'presence',slots:this.presence()});}
 async webSocketError(ws:WebSocket){await this.webSocketClose(ws);}
 async alarm(){const records=await this.ctx.storage.list<{expires:number}>({prefix:'ticket:'});for(const [key,value] of records)if(value.expires<=Date.now())await this.ctx.storage.delete(key);await this.read(true);for(const ws of this.ctx.getWebSockets()){const c=ws.deserializeAttachment() as Connection,last=Math.max(c.lastSeen,this.ctx.getWebSocketAutoResponseTimestamp(ws)?.getTime()||0);if(!this.authorized(c)||Date.now()-last>=45000)ws.close(1008,'Reconnect required');}this.broadcast({v:1,type:'presence',slots:this.presence()});if(this.ctx.getWebSockets().length)await this.ctx.storage.setAlarm(Date.now()+15000);}
}
export default {fetch(){return new Response('Not found',{status:404});}};
